### ISSUE TITLE
Table shortcode button row issue

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#543] opened 2015-05-11 10:34 UTC
Hi
today i have just tried with  table shortcode.  i have just fillup one table column shortcode. and rest of blank.
 then  i have saved table shortcode and reopen  table shortcode. i saw last 2 button option hidden from table shortcode. 
 also i tried to add another row. that option also hide except first column row showing on table shortcode.
http://prntscr.com/73yai0

**Comment by llemurya** [comment] 2015-05-11 12:19
@xpeeder please make an video how to reproduce, because I tried twice and for me it works.Maybe I do something wrong and can't reproduce it.I'am waiting for your response.

**Comment by xpeeder** [comment] 2015-05-11 13:00
@llemurya  check this video  
 http://youtu.be/TkFRUSf-8oE

**Comment by llemurya** [comment] 2015-05-11 13:17
@xpeeder you have only framework activated or the scratch theme is active with unyson?

**Comment by xpeeder** [comment] 2015-05-11 13:21
I am developing a theme.  first column work fine. then i back again in backend to edit  table. that time saw others column  button are not displayed.

**Comment by llemurya** [comment] 2015-05-11 14:08
@xpeeder I followed your stept but for me works , as a proof please watch [this](https://www.youtube.com/watch?v=Bh5M_ONnjO4) video.

**Comment by xpeeder** [comment] 2015-05-11 16:19
@llemurya are you using from table shortcode plugin directory or theme directory ??
I have copied the shortcode from plugin directory to theme shortcode directory
if you are using from theme directory Can you send me your table shortcode through my mail. so i can check starxpeed@gmail.com

Thank you

**Comment by llemurya** [comment] 2015-05-13 10:53
@xpeeder please see what version of the `scratch theme` or `shortcodes extension` you have ,because I tested on the latest versions . If your version is older please update to the latest version of the theme and extension.

**Comment by llemurya** [comment] 2015-05-21 06:59
@xpeeder you resolved this issue? Please give us a feedback.

**Comment by xpeeder** [comment] 2015-05-21 07:05
@llemurya  no brother its not working. if i copy table shortcode in theme directory not working.  but its work from plugin directory. i dont know what i am missing.

Are you tried with theme directory ??

I am always use up to date version.

**Comment by llemurya** [comment] 2015-05-21 07:20
@xpeeder please see the diference from these two files, maybe the `view.php` have different code.

**Comment by llemurya** [comment] 2015-05-29 06:38
@Ataurr you checked the difference from scratch-theme and plugin  `table-shortcode` `view.php` because I suppose what you have an old `view.php` ,please compare your source with the github source.Please give us an answer.Thanks.

**Comment by llemurya** [comment] 2015-06-05 07:59
@Ataurr I close this issue , because I can't reproduce it, and as a proof I gave you a video screen cast in the previous comments. I suppose that is not an Unyson issue.

**Closed by llemurya** 2015-06-05 07:59 UTC
