### ISSUE TITLE
Table element not allowing editing

### ISSUE THREAD

**Issue by jamesflores** [ThemeFuse/Unyson#2788] opened 2017-08-20 09:59 UTC
Version 4.8.1 | Unyson 2.7.4

I was originally running Unyson 2.7.6 but I couldn't see any of the page builder elements for my existing content. I reverted back to 2.7.4 which seems to work, however I cannot edit my table elements. I can see them but cannot click the field to enable text editing in the row/column.

![image](https://user-images.githubusercontent.com/9376054/29493848-fde7038a-85e1-11e7-9d9b-388287363175.png)

**Comment by noesteijver** [comment] 2017-08-28 07:37
Hello,

I'm running into the same problem!

In addition to that: the WP editor has the 'Text' mode selected (the tab), while the editor is in 'Visual' mode. That might have something to do with it.

This way the table becomes pretty much useless. Is there a fix for this?

Hopefully you can help us out!

**Comment by ViorelEremia** [comment] 2017-08-31 07:16
Hi guys,
drop me a line at viorel [ at ] themefuse [ dot ] com with some temporary credentials and link to this issue.

**Comment by noesteijver** [comment] 2017-08-31 13:55
The problem is solved for me now after updating the plugin/extension!

**Closed** 2017-09-11 13:57 UTC
