### ISSUE TITLE
Page Builder always creates one-third grid

### ISSUE THREAD

**Issue by Kosta92** [ThemeFuse/Unyson#405] opened 2015-03-28 19:12 UTC
Hello,
I have a problem with the Page Builder. Whichever columns I choose as a layout, it creates a one-third grid on a website (div class), leaving an empty space on the right side.

Let me explain it.

I want to make a download page similar to <a href="http://offers.hubspot.com/5-steps-to-becoming-a-successful-inbound-marketing-agency">this one</a>.
I go ahead and choose 1/1 column for the heading, and two 1/2 columns for a text on the left and an image on the right side. Page Builder somehow creates an empty third column on the right side and places everything I made in 2/3 of that one-third grid. I am using <a href="http://alxmedia.se/themes/hueman/">Hueman</a> theme.

Screenshots:
* <a href="http://uppix.com/f-Layout5516f80d00189f3d.png">Layout</a>
* <a href="http://uppix.com/f-Problem5516f84400189f3e.png">Problem</a>

So, my question is, where that grid comes from and how to fix this problem?

**Comment by moldcraft** [comment] 2015-03-28 19:47
We don't have such classes as `grid one-third` in [our grid](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/2c2b08a8bcd47dba8cf25eb440f12da357da4b18/static/css/frontend-grid.css#L151-L202) so I think this problem comes from the theme and you should [ask them](https://github.com/AlxMedia/hueman/issues) why this happens. 

Also I can't find any mention of Unyson in their theme ([tgm code](https://github.com/AlxMedia/hueman/blob/7c9d9b43ed666452533c41523fdddb0d89c95089/functions.php#L793-L820)), or you integrated that theme with Unyson by yourself?

**Comment by levan1993** [comment] 2015-03-28 20:27
Hi, the problem is that unyson and your theme have same shortcode name for column and theme overrides it. you can just remove that shortcode

**Comment by moldcraft** [comment] 2015-03-30 16:59
@Kosta92 the @levan1993 's solution works? Can I close this issue?

**Comment by Kosta92** [comment] 2015-03-31 17:07
Thanks @levan1993 , it is working now. I have removed the following shortcode from /functions/shortcodes.php file:

```
/*  Columns / Grid
/* ------------------------------------ */
	function alx_column_shortcode($atts,$content=NULL) {
		extract( shortcode_atts( array(
			'size'	=> 'one-third',
			'last'	=> false
		), $atts) );

		$lastclass=$last?' last':'';
		$output='<div class="grid '.strip_tags($size).$lastclass.'">'.do_shortcode($content).'</div>';
		if($last)
			$output.='<div class="clear"></div>';
		return $output;
	}
	add_shortcode('column','alx_column_shortcode');
```

**Closed** 2015-03-31 17:09 UTC
