### ISSUE TITLE
Page builder CPU usage

### ISSUE THREAD

**Issue by pear1** [ThemeFuse/Unyson#859] opened 2015-09-17 10:42 UTC
Hello, 

I have an issue with page builder high CPU usage in chrome browser.
This happens after resizing page builder window to mobile size (waiting for few seconds) and going back to desktop size. Then CPU usage goes to about 30% and stays for some time (while page builder goes very unresponsive).

Notice: In this page I have about 6 shortcodes with 4 sections and 6 columns.

**Comment by danyj** [comment] 2015-09-17 11:53
ahhh, finally someone has noticed , yes @moldcraft , seems like not only resizing but adding elements to builder , loading templates , moving around , all of it is huge on CPU ,   

look   http://prntscr.com/8hbhz6  added 2 section , 2 columns , moved them around and I am on a monster machine http://prntscr.com/8hbid5

now this crazy thing added inside  ( just testing )

	.fw-options-box-page-builder-box,.fw-options-box-page-builder-box *{
		-webkit-transform: translate3d(0, 0, 0);
		-webkit-perspective: 1000;
		-webkit-backface-visibility:hidden; 
		-webkit-transform-style: preserve-3d; 
		transform-style: preserve-3d;
	}

and than recording , tells me that we do have repaint issue , timeline looks bit better

http://prntscr.com/8hbktv


Now this is what we should be after 
http://prntscr.com/8hbma2

but is not possible since there are many things in wp admin that use fix positions which is messing up chrome.

**Comment by pear1** [comment] 2015-09-17 12:22
Thank you.
At lease now I know that this isn't an issue with my shortocode modifications.
Your fix made some noticeable performance boost, but still isn't very fast on average PC.

**Comment by danyj** [comment] 2015-09-17 12:48
and pay attention anyone  who is using  layerslider or revolution slider ,  they have their script in admin and front even if you dont have slider published, the timer fired you see here http://prntscr.com/8hbktv

comes from rev slider inside admin , they have continuous function that runs every 30ms , things like this will mess with your backend and frontend , when testing unsyon make sure you turn all those off

**Comment by danyj** [comment] 2015-09-17 12:50
@pear1   record timer with only your shortcode running /clicking/scrolling and you will know if it is your script

**Comment by moldcraft** [comment] 2015-12-22 21:16
I have the same problem and it's impossible to work with inspect element https://vid.me/QeT4

I have no idea how to fix it. 

*I thought it is caused by a script, I tried to disable them one by one, also tried to detect if some builder item is causing this, but nothing.*

The only rule I found: If page builder is initially empty and you add how many items you want (for example import a big template), everything will work fine, the window resize will not load the CPU. But once you save the page, after refresh if you do resize everything will freeze.

**Comment by danyj** [comment] 2015-12-22 21:20
@moldcraft  there you go https://github.com/ThemeFuse/Unyson/issues/1101

**Comment by moldcraft** [comment] 2016-01-14 21:52
A had a big page full of shortcodes, after post Update everything was gone (don't worry, it's while developing), the strange thing is that while in builder are no shortcodes, I press F12 (developer tools) and the CPU goes to 100%.

![](https://static.md/73f08d96ee1fc2e38480603834c16e70.png)

**Comment by moldcraft** [comment] 2016-02-11 10:21
I found something. How to reproduce:

1. Open Dashboard page
* Open Developer Tools and go to Timeline tab
* Open a page with builder with lots of elements, just to trigger the bug, but not very much, we will need to stay on the page to wait for CPU to go down from 100% load
* Do fast:

    1. Press Record button (top left corner) in Developer tools Timeline tab
    2. Do a minor page resize (you can move a little Developer Tools header)
    3. Wait for CPU to be 100%, about 3 seconds
    4. Stop recording

5. Wait for CPU to slow down and for Timeline to appear
* Kill the tab from Chrome Task Manager
* In the same tab, change the url to `{site}/wp-admin/` -> Enter.

    It will open the Dashboard page but the Timeline will still be there, and you can inspect it

![](https://static.md/364dfe00dbdb5602a3f96099f21a92d0.png)

Inspecting...

**Comment by moldcraft** [comment] 2016-02-11 10:28
To be able to debug the code, to get actual line numbers, 

* Copy `tinymce.min.js` contents
* Run it through http://jsbeautifier.org/
* Replace the beautified contents

**Comment by moldcraft** [comment] 2016-02-11 11:33
Deleted `tinymce.min.js` contents (made the file empty) and it fixes the problem (no more CPU load on resize).

Trying to find where exactly is the problem...

**Comment by moldcraft** [comment] 2016-02-11 12:06
WordPress uses [tinymce 4.2.8 minified](https://github.com/WordPress/WordPress/blob/4.4.2/wp-includes/js/tinymce/tinymce.min.js#L1). Here is the [dev version](https://raw.githubusercontent.com/tinymce/tinymce-dist/4.2.8/tinymce.js)

**Comment by moldcraft** [comment] 2016-02-11 12:41
I found the problem! [Thanks to Developer Tools](https://static.md/c0f7b811b8d6610b6d118023e8e4d347.png)

Open a page made with builder and execute in browser console:

```js
jQuery(document).trigger( 'wp-window-resized' );
```

**Comment by moldcraft** [comment] 2016-02-11 12:58
[Here](https://github.com/WordPress/WordPress/blob/4.4.2/wp-admin/js/editor-expand.js#L654) is the problem. If I add there `return;` everything works fine.

P.S. Move `editor-expand.js` contents to `editor-expand.min.js`.

Also I noticed that `mceEditor.isHidden() === false`, but it should be `true` because default WP editor is hidden, PageBuilder covers it.

Inspecting...

**Comment by moldcraft** [comment] 2016-02-11 13:39
There `mceEditor.isHidden()` was `false` because [we hide the default WP content editor manually just from html](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/59777a11162e8e84ce66fa713d26f12d361e78d8/includes/page-builder/static/js/editor_integration.js#L46) but `mceEditor.isHidden()` returns the `mceEditor.hidden` property, you can test in browser console:

```js
tinyMCE.get('content').hidden
```

`mceEditor.hidden` is changed when the `.show()` or `.hide()` method is called, which I did in [fix](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/commit/a0eabb8afb51c66a78afaa2167dfe8df315a9a55#diff-6c1b2f67a1a1bf6c0ed0295d9dd98cbcL54).

So the problem was that it thought the editor was visibile and tried to readjust its size on window resize ([code](https://github.com/WordPress/WordPress/blob/4.4.2/wp-admin/js/editor-expand.js#L655-L656)), but it was actually hidden and I think the size recalculation script went in an infinite loop/recursion trying to get DOM sizes/coordinates.

**Comment by moldcraft** [comment] 2016-02-11 17:03
**Please test**

**Comment by pear1** [comment] 2016-02-11 17:41
Hello, 

Just tested and it works much better.

Thank you for your hard work.

**Comment by danyj** [comment] 2016-02-11 21:00
would love to test but im gone till Sunday.  will test as soon as i get back but from reading the notes it makes sense what you found and fixed.

**Comment by moldcraft** [comment] 2016-02-11 21:54
@danyj ok. The PageBuilder extension next release will be in 2 weeks, so take your time.

**Comment by moldcraft** [comment] 2016-02-12 11:48
It happens again...

**Closed** 2016-02-12 12:15 UTC
Labels: help wanted, in progress
