### ISSUE TITLE
New update broke my custom page builder elements

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson#1855] opened 2016-08-02 16:14 UTC
Newest update 6 hours ago, my client reported that custom page builder elements are broken. Please check this. I suppose problem is with page builder extension update.

**Comment by moldcraft** [comment] 2016-08-02 16:16
Hello

Please give more details (screenshots).

**Comment by Jelena1** [comment] 2016-08-02 16:19
In dashboard everything seems fine, custom page builder element is there and has all options. But in front it has only text, no styling, not even images which were custom added for that element.

**Comment by Jelena1** [comment] 2016-08-02 16:30
sent

**Comment by moldcraft** [comment] 2016-08-02 16:49
You mean that PageBuilder had these elements

![](https://static.md/9b16fcb14a262bc3c5078a4b6e6ff7c1.png)

but now it is empty in backend?

**Comment by Jelena1** [comment] 2016-08-02 16:51
it is not empty in backend. there is everything file. it has no styling in
front  end

**Comment by moldcraft** [comment] 2016-08-02 16:52
Sorry, we still don't understand what exactly is the problem. Please give the exact steps to reproduce the problem or give some screenshots with annotations.

**Comment by Jelena1** [comment] 2016-08-02 16:57
Can you login with credentials I sent to you? I have problem with my site
at the moment, please let me know.

So, this is my site
http://rayoflightthemes.com/wordpress-themes/psychologist-psychological-practice-wordpress-theme/

See please that text. It has no styling at all and before this issue it has
styling, text was in color boxes and on center of page with some icons,
images etc...

**Comment by Jelena1** [comment] 2016-08-02 17:08
Dashboard is ok, that element exists in dashboard everything fine but like it don't load styling in front

**Comment by moldcraft** [comment] 2016-08-02 17:13
I can login, but I don't know where that text comes from. It is hardcoded in template? Can you send me ftp details? I need to debug the code

**Comment by Jelena1** [comment] 2016-08-02 17:14
can we share those details in email please? can you reply to my email?

**Comment by moldcraft** [comment] 2016-08-02 17:16
Replied

**Comment by cyclaw** [comment] 2016-08-03 04:53
Hi, it looks like I'm having the same problem on my website. Updated Unyson plugin to 2.5.1.1, updated the Page Builder extension, but now it seems like Page Builder doesn't seem to be "talking" to my theme. I'm using this theme: http://rayoflightthemes.com/insurance_agency_wordpress_theme.html

Can you please help?

**Comment by moldcraft** [comment] 2016-08-03 06:23
We can help if you can give us the steps to reproduce the problem or send me the admin/ftp details to `moldcraft[at]email.com` so I can see and inspect the problem.

**Comment by thednp** [comment] 2016-08-03 10:23
@moldcraft the latest update breaks most shortcodes back-end UI. The static files for shortcodes back-end seem to not be loaded. I'm on localhost for now but we can do a teamviewer any time you want.

**Comment by thednp** [comment] 2016-08-03 10:31
Some screenshots:
![tabs](https://cloud.githubusercontent.com/assets/6761246/17362588/6c05eb2e-597e-11e6-8b96-76abfa538dcf.png)
![table](https://cloud.githubusercontent.com/assets/6761246/17362589/6c082cfe-597e-11e6-9de4-b868334e874c.png)
![textblock](https://cloud.githubusercontent.com/assets/6761246/17362590/6c0e9ddc-597e-11e6-8162-cdef5f6d0731.png)

Also I tried patching with latest download from wordpress.org to no avail.

**Comment by thednp** [comment] 2016-08-03 10:38
I also tried temporarily deleting my custom shortcodes, deactivated wp-shortcodes plugin, deactivated all extensions except page builder, and the results are the same, please look at this asap.

**Comment by moldcraft** [comment] 2016-08-03 10:48
On my side [it works](https://static.md/54db880bcc690104751c3438f8900b71.png)

Please inspect browser console, try to find why the scripts are not loaded or send me admin/ftp details to `moldcraft[at]email.com`.

**Comment by thednp** [comment] 2016-08-03 11:05
@moldcraft please join me on skype, I can provide teamviewer access for you.

**Comment by Jelena1** [comment] 2016-08-03 11:14
@moldcraft  can you please check my site? I sent you ftp in email. Thanks.

**Comment by moldcraft** [comment] 2016-08-03 11:15
I am checking.

**Comment by moldcraft** [comment] 2016-08-03 11:27
Fixed in this release https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/245

**Comment by cyclaw** [comment] 2016-08-03 11:31
Great! Updated the extension and now all is good. Thanks for releasing the fix so quickly.

**Comment by Jelena1** [comment] 2016-08-03 12:10
Thanks!

**Comment by thednp** [comment] 2016-08-03 12:29
Works for me as well, I manually removed the Unyson plugin and reinstalled, it's ok now.

**Closed** 2016-08-03 14:47 UTC

**Comment by Jelena1** [comment] 2016-10-07 15:26
This issue happened again with new update. really frustrating!
