### ISSUE TITLE
Files Restore: The execution failed. Please check error.log

### ISSUE THREAD

**Issue by munkhbayaryo** [ThemeFuse/Unyson#2977] opened 2017-10-25 02:32 UTC
I'm getting this error when I tried to demo content install.

Host: Godaddy
Backup size: 114MB
Error message: **Files Restore: The execution failed. Please check error.log**

Increased these in the php.ini file:

```
max_execution_time = 500 (also tried to 1000, 1500)
max_input_time = -1
max_file_uploads = 120
post_max_size = 64M
upload_max_filesize = 64M
```

Can you help me guys? How to solve it?

**Comment by Ataurr** [comment] 2017-10-25 05:23
This issue should be fixed as soon as possible. Lots of servers cause this issue nowadays.

**Comment by munkhbayaryo** [comment] 2017-10-25 05:50
I decreased file size to 59MB. It's over the **Files Restore**

A new trouble came here:
**Image Sizes Restore: The execution failed. Please check error.log**

Changed the -20 to -40 and tried to more:
```
$max_time = time() + $backups->get_timeout(
    // -SECONDS that one image size can take on a very slow server
    -20 // Fixes https://github.com/ThemeFuse/Unyson/issues/2257#issuecomment-272604225
);
```

Still stopped on Image Sizes Restore progress :(

**Comment by andreiglingeanu** [comment] 2017-10-25 06:25
Hey @Ataurr, are you saying that the problem is from the Godaddy's end? Do you know any details?

**Comment by Ataurr** [comment] 2017-10-25 06:48
@andreiglingeanu This does not occur only on the server also localhost in one of our colleague. The main issue is there no error log available in error log file.
I have tried with `define( 'WP_DEBUG_LOG', true );`
So why is this notice confusing to check error log? 

I will let you know when new site we faced the same issue of our customers.

Thanks

**Comment by andreiglingeanu** [comment] 2017-10-25 06:57
Sometimes those errors get inserted not only in `wp-content/debug.log`, which is where WordPress puts its logs.
Sometimes you need to check the errors of your PHP/Apache server.

If you want to find the location of that file, do it that way:

1. Make an empty PHP file and put the content `<?php phpinfo();` in it
2. Run the file from your browser and look for [`error_log`](https://cl.ly/nI15/Image%202017-10-25%20at%209.55.53%20AM.png) entry
3. If you don't see any value there, it might be worthwhile to assign a value to it from your `php.ini` file

If you're lucky enough, you'll see some useful debug info in that file. Please make sure to post any info you find relevant in here too.

**Comment by ViorelEremia** [comment] 2018-01-16 11:02
Try: ThemeFuse/Unyson-Backups-Extension@f8d5f6a...841413f

**Comment by munkhbayaryo** [comment] 2018-01-22 14:24
Thanks in advice guys! I will try these.

**Comment by ViorelEremia** [comment] 2018-01-22 14:32
@munkhbayaryo try: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/841413f0d6da4e7496751495a06e33ea08a20b62
and read here: http://manual.unyson.io/en/latest/extension/backups/index.html#troubleshooting

**Closed** 2018-01-26 08:49 UTC
Labels: waiting for a reply

**Comment by Taibaaa** [comment] 2021-07-09 09:09
The execution failed. Please check error.log. I'm getting this error again and again. I've increased the execution time and max input time also but still getting this error in madara theme. Anyone here who can help?
