### ISSUE TITLE
"Population Method Posts extension needs configured post categories in post types"

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Unyson#451] opened 2015-04-10 09:00 UTC
Got this error when I used the built in bx-slider extension and selected population from posts. In the options directory, I created **posts.php** file in addition to the already created categories.php, custom.php, options.php.

I also enabled in **config.php**
```php
$cfg['population_methods'] = array('posts', 'categories', 'tags', 'custom');
```

However, the error is still there..

One more question - why when I select to populate it from categories, I don't get the default *Population Method Categories opt 1* and *Population Method Categories opt 2*.
I only see *Choose Category*, *Select Specific Categories* and *Number of Images in the slider*.

**Comment by llemurya** [comment] 2015-04-10 09:20
@pe6o it is not error ,it is a message, please go to your post type , for example post and create categories for this post type, because the slider must have data , it population method is categories ,it must render the categories , if you do not have categories how it can render something. Try create categories , and add posts to these categories. I wait your response.

**Comment by pe6o** [comment] 2015-04-10 10:27
I added some images to the post (The default Hellow World one), created a category and added it to the post. Again I only see *Choose Category*, *Select Specific Categorie*s and *Number of Images in the slider*.

"Fetch images from posts" still doesn't work.

My **posts.php** in *framework-customizations\extensions\media\extensions\slider\extensions\bx-slider\options* consists of the following:

```php
<?php if (!defined('FW')) die('Forbidden');

$options = array(
	'test-id' => array(
		'label' => __('Type of Transition', 'unyson'),
		'desc'  => __('Type of transition between slides', 'unyson'),
		'type'  => 'select',
		'choices' => array(
			'horizontal' => __('Horizontal', 'unyson'),
			'vertical' => __('Vertical', 'unyson'),
			'fade' => __('Fade', 'unyson')
		),
		'value' => 'horizontal',
	)
);
```

**Comment by llemurya** [comment] 2015-04-10 11:11
@pe6o I want to ask if you set featured images for the post what is in your categories, if you don't set the featured images , in front end you will see the slider without items.

**Comment by pe6o** [comment] 2015-04-10 17:45
Oh, so it's for the Featured images. I thought that it fetches all images from the posts. Stupid of me...

**Comment by llemurya** [comment] 2015-04-14 07:18
@pe6o if you find the answer at your question , please close the issue.

**Comment by pe6o** [comment] 2015-04-14 12:19
Yes, I didn't knew that it fetches the featured images.

Closing now.

**Comment by zenics** [comment] 2016-03-01 20:08
keep getting this error,
_Population Method Categories extension needs configured categories in post types_
 I have created a file categories.php and posts.php but I dont understand how to configure the rest. Can someone help me?

**Comment by moldcraft** [comment] 2016-03-01 20:11
Hello @zenics,

Here are the docs http://manual.unyson.io/en/latest/extension/slider/index.html this is the only info I can give, I don't know much about this extension internals.

**Comment by zenics** [comment] 2016-03-01 20:14
I have read all that but still gettinv that error.
-- 
Creative Manner

**Comment by moldcraft** [comment] 2016-03-01 20:18
Try to find the place where this error is thrown and inspect the code to find out why it happens.

**Comment by zenics** [comment] 2016-03-01 20:27
Even the default bx-slider one is not working correctly so I cant find anything to base on.

**Comment by danyj** [comment] 2016-08-18 14:18
@moldcraft  This is still ongoing , I have a category , post with assigned cat , and featured image , same msg

**Comment by danyj** [comment] 2016-08-18 14:19
oh , and one more , event I get the error slider is made

**Comment by moldcraft** [comment] 2016-08-19 10:56
@danyj Please give the exact steps to reproduce (1. 2. 3...)

**Comment by danyj** [comment] 2016-08-19 12:08
Install WP , publish Unyson + slider,  add category, assign cat to hello world post , add featured image. 
click add slider , select Automatically, fetch images from posts, save , you get an error.

**Comment by moldcraft** [comment] 2016-08-23 12:33
@danyj [Can't reproduce](https://vid.me/Mh9A)

**Closed** 2016-08-23 15:54 UTC
