### ISSUE TITLE
How to add specific id to builder sections ?

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#275] opened 2015-02-23 11:44 UTC
I am trying to assign specific id attribute to sections. I tried to use required option for the id but it seems like is not effective on modals #274 . 

Now if I print the builder json I do see that each section in the builder has it's own object. 
But the $attr array is returning only the section options. 
Is there any way for me to get that object index or anything very specific to each section so that I can generate id's from it inside 

    framework-customizations\extensions\shortcodes\shortcodes\section\views\view.php

**Comment by danyj** [comment] 2015-02-23 13:57
I do see that you are adding the section ID in the builder 
http://screencast.com/t/yRSzFKx5e11
but how to add it in frontend?

**Comment by danyj** [comment] 2015-02-25 17:46
Any way we can get this to work ?

**Comment by danyj** [comment] 2015-02-27 13:10
No suggestion on this one?

**Comment by sergiubagrin** [comment] 2015-02-27 23:07
Hi @danyj 

We will check it on monday. @moldcraft is missing 3-4 days and i need to discuss with them.

**Comment by moldcraft** [comment] 2015-03-03 11:03
> I do see that you are adding the section ID in the builder 
> http://screencast.com/t/yRSzFKx5e11

That is temporary unique [backbone Model.cid](http://backbonejs.org/#Model-cid). It is lost/auto-generated on page refresh, it is used to find/identify builder item object (for e.g. [on sortable drag from one column to another](https://github.com/ThemeFuse/Unyson-Builder-Extension/blob/04fef3adaedbf5876ccbdd589d7b44157c27482f/includes/option-types/builder/static/js/builder.js#L391)) and it is used only in backend internally.

> I am trying to assign specific id attribute to sections.

Sorry for asking that late: Why do you need that?

**Comment by danyj** [comment] 2015-03-03 11:58
I am adding all section custom css to head. Background, box model or any section css options. Thus I need the id for each section.

**Comment by danyj** [comment] 2015-03-03 21:07
To make it more clear.  I am against anything like this http://prntscr.com/6cc57f
All of that belongs in head or inside dynamic CSS. 
So in order to keep html clean I used my own class 
https://github.com/YJSGframework/yjsg/blob/master/includes/yjsgcore/classes/yjsg.dochead.class.php#L174 ( feel free to use that approach ) 
and  this way I can do this in section/column/row view  or any theme file 
http://prntscr.com/6cc6jg

and in inc/static.php
I do this 
http://prntscr.com/6cc81n
so this way all that inline goes inside of the head 
http://prntscr.com/6cc8qj

and html is clean. 

Now the auto generated ID  for section/column, helps  me add css in head for that specific column/section only.

**Comment by moldcraft** [comment] 2015-03-03 21:16
I understood what you want to do.
I will try to figure out a (simple) solution in 1-3 days.

**Comment by danyj** [comment] 2015-03-03 21:25
Sure , thank you.  On top of my head I saw it somewhere where you are passing the $atts['atts']
$atts['atts']
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php#L125


if you could just pass this id's as weel to $atts['somekey']
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php#L81 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L74

 it would be great. But you know what you are doing. Thank you for the help!

**Comment by moldcraft** [comment] 2015-03-08 10:12
> @moldcraft I will try to figure out a (simple) solution in 1-3 days.

Sorry, I haven't done it.

I will do it **soon** *(no more exact promises)*.

**Comment by danyj** [comment] 2015-03-08 12:57
Not a problem. I am busy finalizing all theme options and in week or so will move to page options so it is ok for now.

**Comment by moldcraft** [comment] 2015-03-11 14:45
How/Where do you generate the css?

**Comment by danyj** [comment] 2015-03-11 15:10
inside the view I am getting all section/row extra options  and using my dochead class
http://prntscr.com/6fgmnl

**Comment by danyj** [comment] 2015-03-11 15:11
this is basically all I need 

    $atts['sectionid']  //or 
     $atts['rowid']

**Comment by moldcraft** [comment] 2015-03-11 15:12
How you send them to head inside the view? The view is rendered after head when the post content is generated.

**Comment by danyj** [comment] 2015-03-11 15:22
:) you did not believe me before , I mentioned it many times, I used my class to do this. 
https://github.com/YJSGframework/yjsg/blob/master/includes/yjsgcore/classes/yjsg.dochead.class.php

What my class does is just adding your css to the ['cssinhead']  array, 
https://github.com/YJSGframework/yjsg/blob/master/includes/yjsgcore/classes/yjsg.dochead.class.php#L174

and I implode that array in static.php

http://prntscr.com/6fgope

and here is a print_r for ccsinhead on a page where I have builder/sections/rows

http://prntscr.com/6fgpxx

the highlighted testslider is this 
http://prntscr.com/6fgqup

as you see all css is in its place. it was bit of a hassle but is well worth it and html is clean
I take this 

http://prntscr.com/6fgrif

vs this 
http://prntscr.com/6cc57f

any time.

**Comment by danyj** [comment] 2015-03-11 15:33
oh , and the static.php I use to print everything is not section/static.php 

it is theme_name/inc/static.php

**Comment by moldcraft** [comment] 2015-03-12 13:24
I found the solution very simple:

```php
<?php
$auto_id = 'auto-id-'. fw_unique_increment();
ThzDochead::getDocument()->addCssInHead('#'. $auto_id .' { ... }');
?>
<section id="<?php echo $auto_id ?>" ...
```

or I am missing something?

**Comment by danyj** [comment] 2015-03-12 13:33
I was thinking about the same thing and had my own function ( nice to see you have one )  to do that but it does not sit well with me because user might want to add additional css specific to the id and he will never have it right. I know I can add the class for them to style it but if I have 5 sections in the builder this was desired output 

	thz_section_id0
	thz_section_id1
	thz_section_id2
	thz_section_id3
	thz_section_id4

since that is how they are saved in DB for that page 
it is an array with keys 0 - 4

is it hard to add the id inside the $attr array ?

**Comment by moldcraft** [comment] 2015-03-12 13:55
> is it hard to add the id inside the $attr array ?

Shortcodes doesn't have ids, they are stored as non assoc array.

----

Another solution would be:

1. Copy the `hidden` option-type.
2. Rename the type to something like `thz-id`.
3. Change the `_get_value_from_input` method to

	```php
	protected function _get_value_from_input($option, $input_value)
	{
		if (empty($input_value)) {
			return fw_rand_md5();
		} else {
			return (string)$input_value;
		}
	}
	```

4. Add the option in `extensions/shortcodes/shortcodes/section/options.php`

	```php
	'id' => array( 'type' => 'thz-id' ),
	```

If input value will be empty, it will be generated, if it was already generated. it will stay the same.

**Comment by danyj** [comment] 2015-03-12 13:59
ok will try that and by looks of it it might just do what I need. thank you!

**Comment by danyj** [comment] 2015-04-15 17:34
this worked well until I started cloning section in builder via the clone button which clones the previous section id, darn thing

**Comment by moldcraft** [comment] 2015-04-15 17:42
Then

```php
protected function _get_value_from_input($option, $input_value)
{
    //if (empty($input_value)) {
        return fw_rand_md5();
    //} else {
    //    return (string)$input_value;
    //}
}
```

that way all sections will reset their ids on every post save. Anyway, you just need an unique id for the html, so there should be no problems.

**Comment by danyj** [comment] 2015-04-15 18:23
does not work either , I have to open section  popup , save section options and than it changes

**Comment by moldcraft** [comment] 2015-04-15 18:27
hm, not good.

Right now I don't know a solution. I will let you know when I will have any idea.

**Comment by danyj** [comment] 2015-04-15 20:56
bud 

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/70131a2670a4445a432344780b12bde47d0acfdf/includes/fw-option-type-page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L138

all that is missing is this 

    $items[$i]['atts']['custom_item_id'] = $i +1;


http://prntscr.com/6u7647
i'm trying to find same way for  columns but is bit of a maze there but you get the idea. and as you can see here you also used indexes to add custom options to the array

https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/70131a2670a4445a432344780b12bde47d0acfdf/includes/fw-option-type-page-builder/includes/items-corrector/class-page-builder-items-corrector.php#L70

**Comment by danyj** [comment] 2015-04-16 13:05
or this 

    $atts['atts']['custom_item_id'] = fw_rand_md5();


here 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/section/includes/page-builder-section-item/class-page-builder-section-item.php#L130

and here 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/master/shortcodes/column/includes/page-builder-column-item/class-page-builder-column-item.php#L142

I mean if I could extend those 2 files like we do it with their views than that would also work but as you see I am stuck here.

**Comment by moldcraft** [comment] 2015-04-17 00:18
I made some changes in builder (in the above commits) and now on post save the `_get_value_from_input()` method will be executed for all shortcodes options.

In order to test, please download or clone from Github the latest [Shortcodes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) and [PageBuilder](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension) extensions.

The idea remained the same, use a hidden option that generates the unique id https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-78483355

You can test with this option type:

```php
<?php if (!defined('FW')) die('Forbidden');

class FW_Option_Type_Unique_Id extends FW_Option_Type
{
	public function get_type()
	{
		return 'unique-id';
	}

	protected function _get_defaults()
	{
		return array(
			'value' => fw_rand_md5()
		);
	}

	protected function _render($id, $option, $data) {
		return fw_html_tag('input', array(
			'type' => 'text',
			'name' => $option['attr']['name'],
			'id' => $option['attr']['id'],
			'value' => $data['value'],
		));
	}

	private static $ids = array();

	protected function _get_value_from_input($option, $input_value) {
		$id = $input_value;

		if (empty($id)) {
			$id = $option['value'];
		}

		if (empty($id) || !is_string($id)) {
			$id = fw_rand_md5();
		}

		// regenerate if found the same id again
		{
			while (isset(self::$ids[$id])) {
				$id = fw_rand_md5();
			}

			self::$ids[$id] = true;
		}

		return $id;
	}
}
FW_Option_Type::register('FW_Option_Type_Unique_Id');
```

Add it to `{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/options.php`

```php
<?php if (!defined('FW')) die('Forbidden');

$options = array(
	'sid' => array(
		'type' => 'unique-id'
	)
);
```

Testing:

* Add add a section to the builder, don't open the section options popup, then Save the post. The id will be generated.
* Add add a section to the builder, open the section options popup and enter an id manually, then Save the post. The id will remain the same after save/refresh, will not be auto-generated again, that way the users will be able to add custom css to a specific id https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-78479567
* Clone a section (even multiple times), you can open the section options popup to make sure all sections have the same id, then Save the post. The same ids will be auto-generated, only first will remain the same.

For testing purposes I made the option type as `<input type="text" />`, for easy preview and manual change. But for production I think will be better to make it `<input type="hidden" />` (and `'label' => false`) to not bother the user with advanced (maybe useless for him) option.

**Comment by moldcraft** [comment] 2015-04-17 00:22
Also comment [this line](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/4db5677c897a5584996c23aa701fe464d083a28e/class-fw-extension-page-builder.php#L39) please. There is a bug, I didn't fixed it yet.

**Comment by moldcraft** [comment] 2015-04-17 01:02
No need to comment the line anymore, the "problem" was in option-type. I updated the option-type code in comment above.

**Comment by danyj** [comment] 2015-04-17 09:39
thnx for the id fix but you made some major changes in builder and front output that now completely kills my class for adding css inside head, it does not work anymore , 

I was able to do this from section/row view

     ThzDochead::getDocument()->addCssInhead('TESTSTSTSTS');

now it does not work

**Comment by danyj** [comment] 2015-04-17 10:43
I dont know but something is off with latest commits ,  first it messed up my class , than I moved last night backup  and tried paste the new commits again , now my class is ok but the save is resetting section options that worked fine before like  multi-select  switch, I set it to yes , save section options , save edits , open section option the multi is back to no. 

still looking to make sure I got the right files

**Comment by danyj** [comment] 2015-04-17 14:06
Traced it back  this commit is messing up my class    #388 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/89597be5467cb7747a1983a5b7aff797a08c5c0a

to be precise the removal of 
    do_shortcode($post->post_content);


for 3 months everything was working fine and the use of the id for sections/rows was intended because I was relying on the class to put the code inside the head, now I have the id but cant place the code in head. this is just grrrr.

**Comment by danyj** [comment] 2015-04-17 16:31
@moldcraft  this new commit is definitely messing up the switch, it is resetting it back and pag rload seems longer , not sure what other options can get messed up with it but is not right, and that removal of do_shortcode($post) is messing up the rest. this is becoming really exosting and something so simple got so complicated . i catch myself looking for workaround for workarounds where things should be so simple , 
get the id 
add css in head

**Comment by moldcraft** [comment] 2015-04-17 17:02
Thank you for feedback. Don't bother, we will not release the extension without testing. Yesterday I didn't tested it in frontend, there was a little pain to make it work in backend. So when I made it work, I wrote the comment here and went out.

I will inspect it today.

> I catch myself looking for workaround for workarounds where things should be so simple , 
get the id

Well, it's not that simple id, with that auto-generate/unique thing.

> the removal of do_shortcode($post->post_content);

I didn't knew about that (I don't inspect every commit). I will investigate with @GheorgheP why it was removed. I see in place of it was added [an alternative solution for enqueue shortcodes static](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/89597be5467cb7747a1983a5b7aff797a08c5c0a/class-fw-extension-shortcodes.php#L107-L121).

**Comment by danyj** [comment] 2015-04-17 17:18
Thnx for the reply and understanding I am just sitting here hitting walls, for you to understand my trouble and concept here is the info 

ThzDochead  class is included in theme includes

Inside the theme static.php I check that class to see if anything was added to addCssInhead or addJsinhead  array , if yes add it in inline 


    // cssinhead
	if(isset(ThzDochead::getDocument()->dochead['cssinhead'])){	
		$add_css .= implode(ThzDochead::getDocument()->dochead['cssinhead']);
	}
	wp_add_inline_style( THEME_NAME. '-style', $add_css );

this guy is placed inside section/row or any of your shortcode  view.php

    ThzDochead::getDocument()->addCssInhead('sectionid{padding:'.value from padding option."}');

now ,   your  previous 

    do_shortcode($post->post_content); 

was running before

    wp_head();

thus was able to instantiate my class call  from views and add any  custom css inside my css or js class array ,   so all of it was neatly placed inside the head. the alternative you have in place in last commit , does not run the do_shortode , but it is searching trough shortcode for the  shortcode type , and if found it just loads that type css/js,  

this is not bad either , but if we can have some kind of a hook to run our code before head it would solve my issue with css in head

**Comment by danyj** [comment] 2015-04-17 17:20
as for the custom id , this was optimal since it was using the actual section/row array 
https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-93567187

**Comment by danyj** [comment] 2015-04-17 17:30
if you can ad least instantiate the shortcode options  here it might also work 

https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/blob/89597be5467cb7747a1983a5b7aff797a08c5c0a/class-fw-extension-shortcodes.php#L105

I dont know , just thinking out loud

**Comment by moldcraft** [comment] 2015-04-17 18:19
> as for the custom id , this was optimal since it was using the actual section/row array 
> https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-93567187
>
> and we would not need any additional custom option for it

With that solution the section and id will not be connected, if the user will change the sections order in builder (move up/down) the id will be changed [this](https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-78479567) ("user might want to add additional css specific to the id") will not work.

**Comment by danyj** [comment] 2015-04-17 19:10
I see, completely missed that

**Comment by danyj** [comment] 2015-04-17 19:15
but for me it would not matter since the code to add the css is inside the view so what ever the index it will get it right. if i was to do 

     section1{}

inside css file than I would have trouble , but i do 


	$section_id			= 'section-'.$atts['section_id'];
	ThzDochead::getDocument()->addCssInhead($section_id.'{css for this section}');

in view

**Comment by danyj** [comment] 2015-04-17 19:16
either way , bigger issue is the do_shortcode since no matter if i have id or not i cant add css in head

**Comment by moldcraft** [comment] 2015-04-17 19:48
I don't want to add again `do_shortcode()` because I like the new method for calling `enqueue_static()` for each shortcode, it looks more lightweight. So I created [this action](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/90e527d8b6b548f93d742ec89ffb078a9bf09efd?diff=split#diff-d94b2e3085a194eed6fa6ca5413017c2R134).

Let's continue [this test instructions](https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-93866651). *Download the latest [Shortcodes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension) and [Forms](https://github.com/ThemeFuse/Unyson-Forms-Extension) extensions from Github*.

* In `{theme}/framework-customizations/extensions/shortcodes/shortcodes/section/views/view.php` add

    ```php
    <section ... id="section-<?php echo esc_attr($atts['sid']); ?>">
    ```

* In `{theme}/framework-customizations/extensions/shortcodes/hooks.php` add

    ```php
    function _action_fw_ext_shortcodes_section_enqueue_static($data) {
    	$attr = shortcode_parse_atts( $data['atts_string'] );
    
    	$background_color = '#'. rand(0,9) . rand(0,9) . rand(0,9);
    
    	wp_add_inline_style(
        	// this style handle/id should be already enqueued
    		// change it if you not enqueue default section styles but have your own
    		'fw-shortcode-section',
    		'#section-'. $attr['sid'] .' { background-color: '. $background_color .'; }'
    	);
    }
    add_action(
    	'fw_ext_shortcodes_enqueue_static:section',
    	'_action_fw_ext_shortcodes_section_enqueue_static'
    );
    ```

**Comment by danyj** [comment] 2015-04-17 19:57
ok on it  but , is form required for it?

**Comment by moldcraft** [comment] 2015-04-17 20:02
> is form required for it?

I [fixed](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/205839d8c75885506117d7b28a602613f5d8f4ef) in forms a fatal error. *You can try and not download/update the forms, but you will see the error and will have to.* (I don't know why it wasn't reported/happened yet).

----

Now we found another problem, because of [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) all upload options "lost" their values on post save, because of [this](https://github.com/ThemeFuse/Unyson/issues/110#issuecomment-66299518).

If I will not find some workaround, I will change the `upload` and `multi-upload` options to not ignore `$option['value']` (default value set manually, in [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) case it is set "manually").

**Comment by moldcraft** [comment] 2015-04-17 20:03
> is form required for it?

I [fixed](https://github.com/ThemeFuse/Unyson-Forms-Extension/commit/205839d8c75885506117d7b28a602613f5d8f4ef) in forms a fatal error. *You can try and not download/update the forms, but you will see the error and will have to.* (I don't know why it wasn't reported/happened yet).

----

Now we found another problem, because of [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) (which makes the `unique-id` `_get_value_from_input()` to be executed on every post save) all upload options "lost" their values on post save, because of [this](https://github.com/ThemeFuse/Unyson/issues/110#issuecomment-66299518).

If I will not find some workaround, I will change the `upload` and `multi-upload` options to not ignore `$option['value']` (default value set manually, in [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) case it is set "manually").

**Comment by danyj** [comment] 2015-04-17 20:07
the css is added but sid is not there Notice: Undefined index: sid,  and the switch is messed up again , it is being reset as previously advised.

**Comment by moldcraft** [comment] 2015-04-17 20:11
> the css is added but sid is not there Notice: Undefined index: sid

Have you added 

```php
$options = array(
    ...
    'sid' => array( 'type' => 'unique-id' ),
);
```

to `to {theme}/framework-customizations/extensions/shortcodes/shortcodes/section/options.php` ?

> and the switch is messed up again , it is being reset as previously advised.

ok, I will investigate this.

**Comment by danyj** [comment] 2015-04-17 20:14
duh , i used my own name for it , you got me confused a bit there

**Comment by moldcraft** [comment] 2015-04-17 20:15
That's why I said here https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94061237

> Let's continue [this test instructions](https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-93866651)

**Comment by danyj** [comment] 2015-04-17 20:27
darn thing , almost ,  
I thought that 
   

    shortcode_parse_atts( $data['atts_string'] )

will return all section options but is not parsing the arrays 
so i get this instead 

http://prntscr.com/6uz2nk

**Comment by moldcraft** [comment] 2015-04-17 20:30
I know. The page-builder has a special encoding/decoding method that only it knows/controls it. But you need only the section id which is a simple string. Or you need some values from those arrays?

**Comment by danyj** [comment] 2015-04-17 20:31
i need all the options not just the id  , they control everything , layout , backgrounds , colors

**Comment by moldcraft** [comment] 2015-04-17 20:31
Oh, I think you need the colors...

I will see what I can do, maybe I will create a helper page-builder function to encode/decode those strings.

**Comment by danyj** [comment] 2015-04-17 20:35
look 

	function _action_fw_ext_shortcodes_section_enqueue_static($data) {
		$atts = shortcode_parse_atts( $data['atts_string'] );
	
		ThzDochead::getDocument()->addCssInhead('helooooooooo');
	
	}
	add_action(
		'fw_ext_shortcodes_enqueue_static:section',
		'_action_fw_ext_shortcodes_section_enqueue_static'
	);


http://prntscr.com/6uz6h3


so everything I added inside the views to be placed in head can be moved to new hook if I can only get all the options,  
this is even cleaner than before

**Comment by danyj** [comment] 2015-04-17 20:42
I emailed you my section options so that you can test the switch and see what I am up against , 

columns have another such set

**Comment by moldcraft** [comment] 2015-04-17 21:14
Download the latest PageBulder extension from Github and try this:

```php
$attr = shortcode_parse_atts( $data['atts_string'] );
$attr = fw_ext('page-builder')->get_shortcode_atts_coder()->decode_atts( $attr );
```

This won't work if the `page-builder` extension is disabled.

Now I found a [new problem](https://github.com/ThemeFuse/Unyson/issues/469).

**Comment by danyj** [comment] 2015-04-17 21:38
that seems to work fine , all options there so far.  multi pickers still dont work properly

**Comment by danyj** [comment] 2015-04-17 21:44
about the new issue if builder disabled , i seen it before ,  thought that is how you wanted  since you did not make the short codes available outside the editor

**Comment by danyj** [comment] 2015-04-17 21:49
note that I am using the multi picker you last changed 
https://github.com/ThemeFuse/Unyson/issues/442#issuecomment-91811457

**Comment by moldcraft** [comment] 2015-04-17 21:58
> multi pickers still dont work properly

some details? what actually doesn't work?

**Comment by danyj** [comment] 2015-04-17 22:03
is not taking selected value ,  
here video 
http://screencast.com/t/b60Hzu26gZ8

**Comment by danyj** [comment] 2015-04-17 22:38
the bug is in this check 



https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R118

if removed the multies work
multies are arrays and  value is an array 

I used this approach without value set 

https://github.com/ThemeFuse/Scratch-Theme/blob/6665e525a060741f7f78908af03e61c4d974851e/scratch-parent/framework-customizations/theme/options/demo-2.php#L948

but even with this it cant find the value 
https://github.com/ThemeFuse/Scratch-Theme/blob/6665e525a060741f7f78908af03e61c4d974851e/scratch-parent/framework-customizations/theme/options/demo-2.php#L948

**Comment by danyj** [comment] 2015-04-17 22:39
this one to be precise
https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129

**Comment by moldcraft** [comment] 2015-04-17 22:45
Thanks for the investigation. I am already fixing it now. The problem is that it doesn't taking in consideration `$option['value']` at all, it works only with `$input_value`, and event doesn't check if `$input_value` is null ([like other options do](https://github.com/ThemeFuse/Unyson/blob/e6ea353c3772063492a4db015772ec23166f3cd7/framework/includes/option-types/addable-box/class-fw-option-type-addable-box.php#L122-L124)), [it uses it right away](https://github.com/ThemeFuse/Unyson/blob/e6ea353c3772063492a4db015772ec23166f3cd7/framework/includes/option-types/multi-picker/class-fw-option-type-multi-picker.php#L253).

**Comment by moldcraft** [comment] 2015-04-17 23:13
[Fixed](https://github.com/ThemeFuse/Unyson/commit/eee262ef49c992c576899f50f5b8d6c799a35b28) multi-picker and other option types.

> https://github.com/ThemeFuse/Unyson/issues/275#issuecomment-94063667
> Now we found another problem, because of [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) (which makes the `unique-id` option-type `_get_value_from_input()` method to be executed on every post save) all upload options "lost" their values on post save, because of [this](https://github.com/ThemeFuse/Unyson/issues/110#issuecomment-66299518).
>
> If I will not find some workaround, I will change the `upload` and `multi-upload` options to not ignore `$option['value']` (default value set manually, in [this](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/add95cf3cc65cc1f40643970f95c9125255818c7#diff-0a666e20f4726c5eb987b41816b00f28R129) case it is set "manually").

I wrote that without verifying/testing. The problem was actually [here](https://github.com/ThemeFuse/Unyson/commit/eee262ef49c992c576899f50f5b8d6c799a35b28?diff=unified#diff-583c3b559c925151f91f1ced44e7eb4b).

**Comment by moldcraft** [comment] 2015-04-17 23:18
Anything else needed to be fixed in this issue? *(except [this](https://github.com/ThemeFuse/Unyson/issues/469))*

**Comment by danyj** [comment] 2015-04-18 00:13
i took an out bud , 2:30 here, will test first thing in the morning and report back

**Comment by danyj** [comment] 2015-04-18 10:31
This on is for you 
http://prntscr.com/6v66l6

note:  bug found in special heading shortcode


if you use bracket in sub title , it wont display it 

I originally added this 


    Thank you Moldcraft :) 

did not display the sub title

**Comment by moldcraft** [comment] 2015-04-18 12:51
Thank you too, for investigations and feedback.

**Closed by moldcraft** 2015-04-18 12:51 UTC

**Comment by moldcraft** [comment] 2015-05-26 17:31
[This](http://manual.unyson.io/en/latest/extension/shortcodes/index.html#enqueue-shortcode-dynamic-css-in-page-head) (Ctrl+R) will be possible in the next version of Unyson (and page-builder extension).

**Comment by danyj** [comment] 2015-05-26 20:33
Nice work. Question ,  will it work in theme admin when ajax save is on ?

**Comment by moldcraft** [comment] 2015-05-26 20:52
I don't see any connection with Theme Settings.
Give more details pls

**Comment by danyj** [comment] 2015-05-26 20:54
I use builder inside theme options , also have section and columns 
but save is ajax  based not like posts 
so I am not sure if I use unique id in there and save via ajax if it will be able to check the uniqueness

**Comment by moldcraft** [comment] 2015-05-26 21:11
It should work.

**Comment by danyj** [comment] 2015-05-26 21:12
ok , np , if i have trouble  will let you know. thnx for the great work and support.
