### ISSUE TITLE
No longer able to edit pages - UNYSON plugin 

### ISSUE THREAD

**Issue by spinal7000** [ThemeFuse/Unyson#1184] opened 2016-01-05 16:27 UTC
Ibk A
Jan 4, 21:23

All was well until 1:00am yesterday when I could no longer edit my pages...

It gives me a static page with two unresponsive options (page editor and SEO)

When i deactivate the plugin - the entire page becomes jargon
When i reactivate it - I am no longer able to edit the page

I have deleted post revisions

I have no programming skills so please help me with easy words. I am like an intermediate to web design or beginner

**Comment by moldcraft** [comment] 2016-01-05 17:41
Hello,

I can tell you what to try to do in order to find the problem. But if you don't have programming skills, I think will be faster to send me admin and ftp to `moldcraft[at]email.com` and I will investigate your site.

**Comment by spinal7000** [comment] 2016-01-05 18:25
sent

**Comment by Ericson-Kite** [comment] 2016-01-05 18:38
Hi
I'm having the same problema and my partner open a ticket in forum support of Grid Theme:
[http://support.xpeedstudio.com/forums/topic/unyson-update-breaking-the-pages-edition/](http://support.xpeedstudio.com/forums/topic/unyson-update-breaking-the-pages-edition/)
Please we need some resolution **ASAP**

**Comment by moldcraft** [comment] 2016-01-05 19:42
The problem is this https://github.com/ThemeFuse/Unyson/issues/1179 (On your server is PHP 5.2.17).

The fix will be released tomorrow https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/170

----

To fix the problem manually:

1. Open this link

    ```
    {site.domain}/wp-admin/plugin-editor.php?file=unyson%2Fframework%2Fincludes%2Foption-types%2Fswitch%2Fclass-fw-option-type-switch.php
    ```

    or from FTP open

    ```
    wp-content/plugins/unyson/framework/includes/option-types/switch/class-fw-option-type-switch.php
    ```

2. Find `json_last_error() === JSON_ERROR_NONE` and replace it with `!is_null($tmp_json)` so that code will be

    ```php
    if (!is_null($tmp_json)) {
    	$input_value = $tmp_json;
    }
    ```

**Closed by moldcraft** 2016-01-05 19:42 UTC

**Comment by Ericson-Kite** [comment] 2016-01-05 19:50
Perfect!
Problem solved.
Thank you so much.

**Comment by spinal7000** [comment] 2016-01-05 20:31
woohoo!!!! - Thanks you are a life saver!!!!
 

    On Tuesday, January 5, 2016 2:50 PM, Ericson Canavan <notifications@github.com> wrote:
 

 Perfect!
Problem solved.
Thank you so much.—
