### ISSUE TITLE
Unyson Visual Page Builder Content Elements disappearing  from page!

### ISSUE THREAD

**Issue by emuki** [ThemeFuse/Unyson#528] opened 2015-05-08 09:14 UTC
Hi everyone,
I have this strange behavior with the Visual Builder
I have Wordpress 4.2.2 | Unyson 2.2.8

I can effectively build my pages by dragging and dropping elements in sections. But after 1 or 2 days, other content elements disappears 
from the sections leaving the content all in one single text block element 

Here is the well constructed page with all content elements in place:
![unyson erro1](https://cloud.githubusercontent.com/assets/1027695/7533569/d1b5b7a4-f572-11e4-81b9-deb9ee3d78df.png)

After few days, this is what I have left on the page.Other elements have disappeared and their content merged into the text block element
![unyson erro](https://cloud.githubusercontent.com/assets/1027695/7533499/58473f28-f572-11e4-97e0-b8f9c78feb76.png)

When I clicked to view the source of the text block, I found out that the source of other elements have be included in the text block:
![unyson erro2](https://cloud.githubusercontent.com/assets/1027695/7533628/54f36eb8-f573-11e4-9626-874882ff467b.png)

What could be the reason behind this? Please help

**Comment by moldcraft** [comment] 2015-05-08 09:22
Hello

> After few days, this is what I have left on the page.

So you did nothing, and the elements just disappeared?

----

There was a [similar problem](https://github.com/ThemeFuse/Unyson/issues/500#issuecomment-100163589) with the preview.

Sorry but I can't help until you'll give the steps to reproduce this.

**Comment by emuki** [comment] 2015-05-08 09:32
Yes @moldcraft and this seems to be a bug that's yet to be handled. It's really an issue

**Comment by moldcraft** [comment] 2015-05-08 09:37
Yes it's a bug of course, but I need to know how to reproduce it in order to fix it.

Please make sure you have the latest extensions installed: Go to updates page and click [Check Again](http://static.md/f461fcd84e465ff7f7314180177d6806.png) the make sure you install all the updates (if there are some).
If this problem will happen again, please let us know.

**Comment by emuki** [comment] 2015-05-08 09:40
Yes @moldcraft I have the latest version
Is there anyway I can give you pass to my wp admin so you can check that out?

**Comment by moldcraft** [comment] 2015-05-08 09:41
You can send me the pass to `moldcraft[at]email.com`

**Comment by emuki** [comment] 2015-05-08 09:43
Ok sending you the info right away @moldcraft

**Comment by moldcraft** [comment] 2015-05-08 13:52
*Sorry for late reply, I was busy with fixing [some bugs](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/64).*

There was [extension updates available](https://static.md/50ac77cc4f0448cd027d17fbbaa8dfd3.png), I [installed them](https://static.md/0a7c9cbc54553109abc7d97bdfaae55e.png).
I updated a page with minor changes (then set everything back how it was), opened the Preview, and everything seems to work fine.
I think the problem was in Preview (which was fixed in the latest PageBuilder update).
Today a colleague also experienced this problem with a page (after Preview he lost the content), and after extensions update the bug was no longer there.

**Comment by duongancol** [comment] 2015-05-10 10:35
I installed the latest version of Unyson and Page builder extension. When I click to revision, choose a revision and click Restore. This error appeared. Please check it.

**Comment by moldcraft** [comment] 2015-05-10 10:40
The revision you restored from, was created before the bug was fixed?
If yes, that revision is "broken" and does not contain any builder data, if you restore from it, you delete all post options.

**Comment by duongancol** [comment] 2015-05-10 10:42
I tried to create new page to test revision, and the bug didn't happen. So I think you're right.

**Closed** 2015-05-11 08:32 UTC

**Comment by emuki** [comment] 2015-05-11 08:35
Thanks @moldcraft for the job you did. I'll ask my admin to try it out this week and let's see how it goes
