### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by Jelena1** [ThemeFuse/Unyson#660] opened 2015-06-09 12:27 UTC
I got message today about update in dashboard for one of extensions for Unyson (didn't pay attention which one) and I did update and after that all my custom post types are not visible anymore in dashboard. They are visible if I deactivate Unyson: What is going on?

**Comment by moldcraft** [comment] 2015-06-09 12:51
Can you please disable extensions one by one to detect which extension is causing the problem?

**Comment by Jelena1** [comment] 2015-06-09 13:23
It is pagebuilder extension, only extension I'm using. Even blog posts doesn't work: If any of custom post types links in dashboard are clicked only blank page appears. When this extension is disabled all works again.

**Comment by moldcraft** [comment] 2015-06-09 13:50
> all my custom post types

Can you give me your `register_post_type()` functions and other details so I can reproduce this problem?

**Comment by Jelena1** [comment] 2015-06-09 14:00
add_action('init', 'mytheme_one_page_section'); 

function mytheme_one_page_section()  {  
  $labels = array(  
    'name' => __('Page Sections', 'text'),  
    'singular_name' => __('Page Sections', 'text'),  
    'add_new' => __('Add New Section', 'text'),  
    'add_new_item' => __('Add New Section', 'text'),  
    'edit_item' => __('Edit section', 'text'),  
    'new_item' => __('New section', 'text'),  
    'view_item' => __('View section', 'text'),  
    'search_items' => __('Search sections', 'text'),  
    'not_found' =>  __('No sections found', 'text'),  
    'not_found_in_trash' => __('No sections found in Trash', 'text'),  
    'parent_item_colon' => '' 
  );  
  
  $args = array(  
    'labels' => $labels,  
    'public' => true,  
    'publicly_queryable' => false,  
    'show_ui' => true,  
    'query_var' => true,
    'rewrite' => true,  
    'capability_type' => 'post',
    'show_in_nav_menus' => true,  	 
    'hierarchical' => false, 
    'exclude_from_search' => true,	 
    'menu_position' => 4, 
    'supports' => array( 'title', 'editor')  
  );  
  register_post_type('page-sections',$args);  
} 

That is one of CPT-s but also those with rewrite "false" and  'rewrite' => array('slug' => 'slugname','with_front' => false),  doesn't work and most important - blog posts doesn't work too.

And this is php error I got when I refreshed one of posts in that CPT after Unyson activation: 

Parse error: syntax error, unexpected T_STRING in /home/...wp-content/plugins/unyson/framework/extensions/forms/includes/option-types/form-builder/items/recaptcha/class-fw-option-type-form-builder-item-recaptcha.php on line 158

**Comment by danyj** [comment] 2015-06-09 14:05
that is a namespace , 
https://github.com/ThemeFuse/Unyson-Forms-Extension/blob/master/includes/option-types/form-builder/items/recaptcha/class-fw-option-type-form-builder-item-recaptcha.php#L158

what php version are you on ?

**Comment by danyj** [comment] 2015-06-09 14:08
@Jelena1  u must be on php 5.2 , thus all the issues

**Comment by danyj** [comment] 2015-06-09 14:09
here , http://stackoverflow.com/a/12650867/594423

**Comment by Jelena1** [comment] 2015-06-09 14:35
Yes it was php issue, now I'm using 5.3 php on that website and no problem anymore. But WP still supports 5.2.4 php version, Unyson should too, especially should be without this unexpected issues with updates.

**Comment by danyj** [comment] 2015-06-09 14:38
@Jelena1   yes , but latest php version is 5.6+,  5.2  is one of the buggies and recommendation is 5.3 and up , I understand your point but 5.2 is missing many things which can make coding such an excellent framework much harder.  

However a notice should be there  that Unyson requires 5.3+   or this should be fixed to work in 5.2, 

at least we know what the issue is. is easier from here :)

**Comment by Jelena1** [comment] 2015-06-09 14:42
I'm not aware Unyson requires 5.3+ if it is official then it is fine I just don't like unexpected errors like this one. Thanks for help.

**Comment by danyj** [comment] 2015-06-09 14:43
@moldcraft   browse issues , I think there are 2 or 3 more that point to something else but could actually be php version.   in all cases they use builder " only"  ( back to folder structure issue, people dont know whet they actually have installed)

**Comment by GheorgheP** [comment] 2015-06-11 11:28
Hi,

I'm sorry for created situation, there was added by mistake the Google Recaptcha Library with namespaces.

The new version of forms with removed namespace will be released tomorrow.

Really sorry.

**Closed** 2015-06-11 11:39 UTC
Labels: bug
