### ISSUE TITLE
Popup + wp editor + create gallery =  javascript error

### ISSUE THREAD

**Issue by ivandotv** [ThemeFuse/Unyson#1957] opened 2016-09-01 19:18 UTC
If I have a wp editor inside the popup , and I go to `add media` -> `create gallery` 
- Create the gallery.
- Gallery gets inserted inside the wp editor.
- Save the popup (popup closes)
-  Open the popup , try to click on the interface for editing the gallery, and you get  `wp-tinymce` errors.
- The same thing happens when inserting images , but not always. In case of the gallery it is always.
- I think it has something to do with the "overlay interface for the gallery (edit / close) buttons.
- After the first error, you get those same errors no matter where you click (anywhere on the page)
- Keep in mind that editor correctly saves the values even with those errors.
  Please take a look at this .gif (big gif **> 4MB**)
  ![peek 2016-09-01 21-12_send](https://cloud.githubusercontent.com/assets/390700/18180901/3730e8f0-7089-11e6-910e-cee8d89ecc82.gif)

**Comment by andreiglingeanu** [comment] 2016-09-01 20:39
@ivandotv I'll take a look.

**Comment by ivandotv** [comment] 2016-09-02 16:37
It issue is very annoying because admin debug button turns red. And the user thinks that something is broken.

**Comment by ivandotv** [comment] 2016-09-05 10:47
I am not familiar with tinymce library, but maybe when the popup closes there needs to be some kind of a cleanup for wp editor ( destroy tinymce instance) ?

**Comment by moldcraft** [comment] 2016-09-06 19:06
@andreiglingeanu If you will have time, you can also inspect the case

WP Shortcodes > Accordion > tab > wp-editor > Accordion > tab > wp-editor ...

so deeply nested shortcodes cause wp-editor init error. You can notice the problem here https://vid.me/8LwZ

**Comment by andreiglingeanu** [comment] 2016-09-07 06:54
> Are you doing any cleanup in the popup before it is closed

There's no teardown functionality for any option type on modal close. But, on modal close, its HTML is emptied out (elements remain the same, in memory), without removing any event that is attached to the `document`, which kinda makes me think about some possible memory leaks and too much events listeners being around.

As a matter of fact, each option type is initialised on each modal open (which generates a `fw:options:init` event, that any option type is listening to, [by convention](https://github.com/ThemeFuse/Unyson/blob/v2.6.1/framework/includes/option-types/wp-editor/static/scripts.js#L134)). And each option type have its own method of running initialisation just once. Some of them rely on a `fw-initialized` HTML class attached to parent option type node, some of them rely on simple JS techniques.

<hr>

What I'm suggesting is to introduce some `fw:options:teardown` event, which should be triggered on each modal close and `$elements` should be passed as data. And each option type should behave as they like to this event. Some of them (most simple ones) should keep relying on HTML classes for that behavior.

The thing is that before opening nested modals (the ones that have their position in [stack > 1](https://github.com/ThemeFuse/Unyson/blob/v2.6.1/framework/static/js/fw.js#L597-L599)) you should trigger `fw:options:teardown`, then `fw:options:init` for the new modal - that's the most difficult part to get right, assuming `fw:options:teardown` may do some async stuff that should be completed before even trying to open a nested modal (maybe collect promises in a mutable array and wait for them to be resolved via [`jQuery.when`](https://api.jquery.com/jquery.when/)?).

I'll happily review (and help to get a complete) pull request for this thing.

<hr>

After all, you guys are trying to achieve advanced stuff, which is practically impossible without trying hard to learn how those modals are working under the hood. You should learn advanced stuff in order to get advanced and kick ass looking things.

<hr>

_I'll look today into gallery stuff._

**Comment by ivandotv** [comment] 2016-09-07 10:50
I didn't know you could launch modals inside modals. And quite frankly you already can do a lot of things with the framework, so maybe you could just remove the functionality of modals inside modals, and make your life easier.
Or create a community discussion to see if anyone is using this.

**Comment by andreiglingeanu** [comment] 2016-09-07 10:54
> I didn't know you could launch modals inside modals

That's not quite correct. It just maintains a stack of current opened modals, so that you can give them a little bit of calculated padding for each one, so that the user will be aware about the context.

> so maybe you could just remove the functionality of modals inside modals

No way. Everyone's using `popup` option type in another modals. And you can have another `popup` in nested `popup`s.

**Comment by ivandotv** [comment] 2016-09-07 12:42
It is definetely problems with that  "edit/remove" gallery interface.
Check out what happens when I switch tabs from **background** tab to **custom content** tab, while there is a gallery inside the wp-editor.
That interface is not removed, and I believe that is the code that makes all those errors.
![www gifcreator me_3sfv5k](https://cloud.githubusercontent.com/assets/390700/18312204/d756ad78-7508-11e6-8d31-9a0ce7b3c5d7.gif)

**Comment by moldcraft** [comment] 2016-09-07 13:32
Just my 2 cents: There was the same problem with link editor tooltip, and I fixed it [like this](https://github.com/ThemeFuse/Unyson/blob/e68ed6acbb300d3223cbdf79783ac8afa0911d95/framework/includes/option-types/wp-editor/static/scripts.js#L112-L116)

**Comment by andreiglingeanu** [comment] 2016-09-08 08:17
Trying this now. I can't reproduce none of this error with Scratch Theme.

**Comment by andreiglingeanu** [comment] 2016-09-08 08:19
Yes, it works fine, even with multi-level popups.

My [`settings.php` in Scratch](https://gist.github.com/andreiglingeanu/56d25453a4071b5730786395ac91ede4)

**Comment by andreiglingeanu** [comment] 2016-09-08 09:01
@moldcraft 

> @andreiglingeanu If you will have time, you can also inspect the case
> WP Shortcodes > Accordion > tab > wp-editor > Accordion > tab > wp-editor ...

No one cares about such a deeply nested structure. Let's not even bother.

**Comment by ivandotv** [comment] 2016-09-08 11:44
@andreiglingeanu 
I have tested your settings and even added tabs and multi-picker inside the popup.
And I can't reproduce the error.
Maybe it has something to do with my particular set of options.
I will investigate it further, for now let's keep the issue open.

**Comment by moldcraft** [comment] 2016-09-08 13:30
> @andreiglingeanu ... Let's not even bother.

Ok

**Closed** 2017-04-25 12:19 UTC
Labels: can't reproduce
