### ISSUE TITLE
Shortcodes button doesn't appear in default wp-editor toolbar. (post.php and page.php)

### ISSUE THREAD

**Issue by azharijelek** [ThemeFuse/Unyson#1484] opened 2016-04-19 05:32 UTC
While I can see there is shortcode button inside toolbar of default wp-editor with Unsyon's Scratch theme, why my theme won't displays the shorcode button?

is there special hook to display that? or did I do something stupid? please help :(

Screenshot: http://www.awesomescreenshot.com/image/1177546/953c4bdee988a44f4cda863e029e1057

**Comment by azharijelek** [comment] 2016-04-19 06:52
Figured the problem. Add Rich Text option type in post metabox to get the shortcodes button appears.

Why we need to have _rich text_ option type in <b>metabox</b> to get the shortcode button appears in default WordPress text editor toolbar? It doesn't make any sense.

**Comment by moldcraft** [comment] 2016-04-19 11:33
Try to disable all plugins except Unyson, maybe the problem is in one of them.

I have installed TheCore theme and the button is there without rich text in metabox.

**Comment by azharijelek** [comment] 2016-04-19 16:24
Hi @moldcraft, thank you for your reply. 

I did the following:

1. Install fresh WordPress installation
2. Only unyson plugin that has activated. (with page builder installed & activated)
3. it uses Unsyon's scratch-parent theme
4. Remove **wp-editor** type option in metabox. (../scratch-parent/framework-customizations/theme/options/posts/post.php)
5. still missing the button.

The only working solution for me is just use wp-editor type in metabox, and then I make it disappear`display:none` with css.

I believe that this file:
`unyson\framework\extensions\shortcodes\extensions\page-builder\extensions\editor-shortcodes\static\js\plugin.js` has something to do with this issue. 
This .js file won't be loaded unless there is wp-editor option type rendered in admin page.

I'll just close this issue until I can make a tweak myself.

**Comment by stefanhurezan** [comment] 2016-04-25 09:14
Hello guys,

I have the same problem! I started building a website using some functions of Unyson and suddenly the shortcodes button dissapeared. Is there any update on a fix?

**Comment by moldcraft** [comment] 2016-04-25 09:16
I activated Twenty Sixteen theme, and the button is not there.

**Comment by moldcraft** [comment] 2016-04-25 11:36
The problem is that `wp_editor()` is meant to be used only once in page (or something like that), in short: it is tricky to make it work multiple times on page. In this case, in shortcodes default options where `wp-editor` options is used, there was set the `teeny` parameter (I don't know why) and it messed [WP Editor internal "very smart" logic](https://github.com/WordPress/WordPress/blob/4.5/wp-includes/class-wp-editor.php#L349-L361). I just [removed the `teeny` param](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/commit/c91e456a3bab710a00823e37acf8bc682255ec6f) from those options and don't bother why exactly the problem happens.

**Comment by stefanhurezan** [comment] 2016-04-25 11:49
Thank you! It's working, it just messed up all the buttons I already added in my pages, but that I can redo quickly!

**Comment by moldcraft** [comment] 2016-04-25 11:59
I just [released](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/releases/tag/v1.3.12) a new Shortcodes extension version without [approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval) because it contains [very few changes](https://github.com/ThemeFuse/Unyson-Shortcodes-Extension/compare/v1.3.11...v1.3.12).

**Comment by BiJeiTi** [comment] 2016-05-06 13:30
I still have the same problem. I'm using Unyson as part of the theme "Everglade by Ciaotheme".
Now I try also to use your new release but the problem remain. No shortcode button appear

**Comment by moldcraft** [comment] 2016-05-06 14:30
Please check post options in `{theme}/framework-customizations/theme/options/*` if there are `wp-editor` options with `teeny` parameter. If yes, remove that parameter and check if the button appears.

**Comment by BiJeiTi** [comment] 2016-05-06 14:54
I try to check but unfortunatly I don't found any wp-editor setting.
But I see that in my wp editor now there isn't any other button of external plug-in. For example no button also from revolution slider. I try to investigate.

**Comment by moldcraft** [comment] 2016-05-06 14:58
@BiJeiTi Please add [here](https://github.com/ThemeFuse/Unyson/blob/v2.5.3/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L120) `unset($option['teeny']);`

**Comment by BiJeiTi** [comment] 2016-05-06 15:19
@moldcraft you are fantastic!
Problem solved!
I have only noted that my "class-fw-option-type-wp-editor.php" file is longher compared to the file in this site. 448 line instead of 220. It can be that is only blank line...I don't know. But now the shortcode button are working!

**Comment by jashwant** [comment] 2016-05-14 14:01
@moldcraft , Is it fixed ? Because, I am encountering the same issue, but opposite in behavior.

If I have field of type `wp-editor` in metabox, shortcode does not appear. If I remove `wp-editor` from metabox, shortcode appears on `wp_editor` of page.

**Comment by moldcraft** [comment] 2016-05-14 19:02
@jashwant [This is the fix](https://github.com/ThemeFuse/Unyson/blob/c6f8cd9c2726e30d64c6e7d8825fdfca8613d776/framework/includes/option-types/wp-editor/class-fw-option-type-wp-editor.php#L127), it will be included in the next release

**Comment by jashwant** [comment] 2016-05-15 05:41
Mentioned commit, does not fix it for me. 
Not sure, what is causing the issue, but if I comment out below code, it works. 

```php
{
	$settings = $this->get_option_settings($id, $option, $data);

	unset($settings['teeny']); // I don't know why, but it breaks the default post wp editor

	ob_start();
	wp_editor( $settings['value'], $settings['id'], $settings['settings'] );
	ob_end_clean();
}
```

**Comment by moldcraft** [comment] 2016-05-15 06:51
> If I have field of type wp-editor in metabox

Please give your option array and I will test it on my side.

**Comment by jashwant** [comment] 2016-05-15 07:04
@moldcraft ,

I am reduced my option array to this,

```php
$options = array(
	'my_editor'                      => array(
		'label' => __( 'Editor', 'unyson' ),
		'type'  => 'textarea'
	)
);
```

1. I've disabled all plugins,
2. Using 'scratch-parent' theme
3. Running wordpress 4.0 & php 5.5.9-1ubuntu4.14

**Comment by moldcraft** [comment] 2016-05-15 07:09
> wordpress **4.0**

?

**Comment by jashwant** [comment] 2016-05-15 07:11
Yes. Wordpress 4.0. 

Isn't it supported ?

At getting started page, I see this:

> Minimum Requirements
> 
> WordPress 4.0 or greater
> PHP version 5.2.4 or greater
> MySQL version 5.0 or greater

**Comment by moldcraft** [comment] 2016-05-15 09:07
Yes.

**Comment by moldcraft** [comment] 2016-05-17 11:11
I enabled Scratch Theme, added in `\wp-content\themes\scratch\scratch-parent\framework-customizations\theme\options\posts\page.php`

```php
$options = array(
	'my_editor' => array(
		'label' => __( 'Editor', 'unyson' ),
		'type'  => 'wp-editor',
	)
);
```

And it works

![](https://static.md/87857d2ecbdcd9922d929842c246bd86.png)

**Comment by jashwant** [comment] 2016-05-17 11:25
@moldcraft , Is it wordpress 4.0 ? Because, I check just now that it works fine on wordpress 4.5.2, but not on 4.0

**Comment by moldcraft** [comment] 2016-05-17 11:40
No, it is latest version. Why you don't update to latest WP version?

**Comment by jashwant** [comment] 2016-05-17 12:06
I am developing a theme ( which I intend to sell in future ). And I want to support wordpress 4.0 and above.

So, I am developing on 4.0 to ensure proper support.

**Comment by moldcraft** [comment] 2016-05-17 12:57
* [4.4.3](https://wordpress.org/wordpress-4.4.3.tar.gz) Works
* [4.3.4](https://wordpress.org/wordpress-4.3.4.tar.gz) Works
* [4.2.8](https://wordpress.org/wordpress-4.2.8.tar.gz) [Not Working](https://static.md/fa35891e8708a0b19c13b852f0cc25b2.png)

I will update the required WP version from 4.0 to 4.3 https://www.gravityhelp.com/wordpress-version-requirements-for-support/

**Closed** 2016-05-17 13:02 UTC
Labels: bug, can't reproduce

**Comment by jashwant** [comment] 2016-05-17 13:11
Thanks for updating. I think it's right to not support that old wordpress. I'll think about it myself for my theme.
Also, you may also want to update [Getting started page] (http://manual.unyson.io/en/latest/#minimum-requirements), to reflect the minimum wordpress requirement.

**Comment by brandonpruitt** [comment] 2016-05-27 15:32
Hello.  I have Wordpress 4.5.2 and Unyson 2.5.5, but I am still having the very same problem.  I have disabled all plugins except Unyson as part of testing, but the shortcodes button remains missing.

**Comment by moldcraft** [comment] 2016-05-27 16:06
Hello, this happens with default WP theme?

**Comment by brandonpruitt** [comment] 2016-06-07 14:59
@moldcraft 

I've tried it on default WP theme, with no luck, but my main theme is Woffice, and it is the most up-to-date one.

**Comment by moldcraft** [comment] 2016-06-07 15:03
@brandonpruitt Can you send me admin/ftp details to `moldcraft[at]email.com`? And I will inspect the code

**Comment by moldcraft** [comment] 2016-06-08 10:20
@brandonpruitt Thank you for details. Your site doesn't have **Dashboard > Updates** menu and extensions are not up-to-date. You have [PageBuilder v1.4.2](https://static.md/5b09f44f595b9e5815e606e90457b806.png) installed, but [latest version is v1.5.5](https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/releases)

**Comment by pe6o** [comment] 2016-08-05 10:19
After updating to the latest version of the extensions, the Shortcodes button is no longer there. It was before updating.
