### ISSUE TITLE
Unyson Extensions Page : Blank

### ISSUE THREAD

**Issue by 2Fwebd** [ThemeFuse/Unyson#794] opened 2015-08-12 17:52 UTC
Hi there, 

Nothing urgent here, it's just that I have many feedbacks about it : 
Whenever there is a PHP error or JS error the main div that contains the extensions get a opacity: 0;
![unyson_ _ivy_league_academy_ _wordpress](https://cloud.githubusercontent.com/assets/5446124/9231978/89ec430e-4101-11e5-8be0-27d5b3502cb5.jpg)

Maybe it should be more "user-friendly" to show a message or something else than a blank page ? With more details about it ;)

Just a suggestion. 

Best regards,

2F

**Comment by danyj** [comment] 2015-08-12 19:14
:+1:   same here , on every error we see blank page only , must have error logs open all the time to see what the issue is,    do fw_print() rather than blank page

**Comment by 2Fwebd** [comment] 2015-09-18 16:26
Any news about it ? :)

**Comment by moldcraft** [comment] 2015-09-18 16:46
Sorry, no. I'll take a look tomorrow. The fix will be included in v2.4.8

**Comment by 2Fwebd** [comment] 2015-09-18 17:01
Thank you so much @moldcraft ! It may seems a bit useless but to troubleshoot issues from extensions it's really useful for us :)

**Comment by moldcraft** [comment] 2015-09-19 18:33
*Did not have time for this today, I'll try tomorrow.*

**Comment by moldcraft** [comment] 2015-09-20 10:25
test it please

**Closed** 2015-09-20 10:25 UTC
Labels: enhancement

**Comment by 2Fwebd** [comment] 2015-09-20 11:12
Hi!

It works pretty well : 
![unyson_ _woffice_dev_ _wordpress_and_classes](https://cloud.githubusercontent.com/assets/5446124/9980421/3552a516-5f99-11e5-9f05-10892b9683be.jpg)

At least we can see which extension has an issue as it's the last one displayed ;)
