### ISSUE TITLE
Multi picker is not working more, important & urgent

### ISSUE THREAD

**Issue by WPJobs** [ThemeFuse/Unyson#1449] opened 2016-04-12 18:23 UTC
Hello!

This code worked before, but not working since latest Unyson update:
```
'rss_feed' => array(
	'type' => 'multi-picker',
	'label' => false,
	'desc' => false,
	'picker' => array(
		'enabled' => array(
			'label' => esc_html__( 'RSS Feed', 'mytheme' ),
			'type' => 'switch',
			'left-choice' => array(
				'value' => 'false',
				'label' => esc_html__( 'Disabled', 'mytheme' )
			),
			'right-choice' => array(
				'value' => 'true',
				'label' => esc_html__( 'Enabled', 'mytheme' )
			),
			'value' => 'true',
		)
	),
	'choices' => array(
		'true' => array(

			'display_thumbnails_in_rss' => array(
				'label' => esc_html__( 'Add post thumbnails to the RSS Feed', 'mytheme' ),
				'type' => 'switch',
				'desc' => esc_html__( 'If enabled, post thumbnail will be added for each post in your RSS feed', 'mytheme' ),
				'right-choice' => array(
					'value' => 'true',
					'label' => esc_html__( 'Yes', 'mytheme' )
				),
				'left-choice' => array(
					'value' => 'false',
					'label' => esc_html__( 'No', 'mytheme' )
				),
				'value' => 'true',
			),

		),
	),
	'show_borders' => false,
),
```

Unyson doesn't save the value and i always get "true", switcher doesn't work in admin panel

`var_dump( filter_var( fw_get_db_settings_option( 'rss_feed/enabled' ), FILTER_VALIDATE_BOOLEAN ) );`

why this happened? I have quite a lot of such structures in several themes and it is very bad that it just stopped working :( please help ASAP

**Comment by moldcraft** [comment] 2016-04-12 19:45
I added the above code in 

```
{theme}/framework-customizations/theme/options/settings.php
```

and tried all switches combinations and everything is saved fine.

How to test/reproduce this?

**Comment by WPJobs** [comment] 2016-04-12 19:47
Thank you for a really fast answer! Could you leave your email here and i'll provide you test FTP website

**Comment by moldcraft** [comment] 2016-04-12 19:51
P.S. I think it's a bad idea to use bool values as string,[ because of this](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/core/components/backend.php#L1154-L1166). Instead of `'value' => 'true|false'` better use another words, for e.g. `'value' => 'enabled|disabled'`.

P.P.S. Have you tested your theme [before we released latest version](https://github.com/ThemeFuse/Unyson-Extensions-Approval)?

`moldcraft[at]email.com`

**Comment by WPJobs** [comment] 2016-04-12 20:06
You made some changes due to this ticket i believe (15 days ago) https://github.com/ThemeFuse/Unyson/issues/1394 but, there was no such restrictions before :) how about themes, created before these changes?

p.s. I tested my theme 30 days ago and all worked perfectly (ThemeForest review new themes in 30+ days), and now, when some users bought my theme, i have a problem with Theme options

**Comment by WPJobs** [comment] 2016-04-12 20:17
p.s. is it possible to add some backward compatibility option e.g. in theme manifest for themes, created before these changes?

**Comment by moldcraft** [comment] 2016-04-12 20:48
I will add backward compatibility but a new version will be in a few days

**Comment by WPJobs** [comment] 2016-04-12 20:52
thank you so much!

**Comment by WPJobs** [comment] 2016-04-12 22:04
if this may help: i have just noticed that multi-picker doesn't work even if i use "yes / no" (not booleans!) as values, e.g.: "autoplay" option will be always "disabled" in a Page Builder popup:

```

<?php

'autoplay' => array(
	'type' => 'multi-picker',
	'label' => false,
	'desc' => false,
	'picker' => array(
		'enabled' => array(
			'label' => esc_html__( 'Autoplay', 'mytheme' ),
			'type' => 'switch',
			'left-choice' => array(
				'value' => 'no',
				'label' => esc_html__( 'Disabled', 'mytheme' )
			),
			'right-choice' => array(
				'value' => 'yes',
				'label' => esc_html__( 'Enabled', 'mytheme' )
			),
			'value' => 'no',
		)
	),
	'choices' => array(
		'yes' => array(
			'autoplay_speed' => array(
				'type'  => 'text',
				'label' => esc_html__('Autoplay speed', 'mytheme'),
				'desc'  => esc_html__('in milliseconds, e.g.: 2000 = 2 seconds', 'mytheme'),
			),
		)
	)
),

```

**Comment by danyj** [comment] 2016-04-12 22:14
@WPJobs  I jus tested mine and they work ok , try this 


	'test_switch' => array(
		'type' => 'multi-picker',
			'label' => false,
			'desc' => false,
			'picker' => array(
				'picked' => array(
					'label' => __('Label', 'fw'),
					'desc' => __('Desc', 'fw'),
					'type' => 'switch',
					'right-choice' => array(
						'value' => 'hide',
						'label' => __('Hide', 'fw')
					),
					'left-choice' => array(
						'value' => 'show',
						'label' => __('Show', 'fw')
					),
					'value' => 'show'
				)
			),
			'choices' => array(
				'show' => array(
				
				),
			)			
	),

**Comment by WPJobs** [comment] 2016-04-12 22:20
@danyj i'm so sorry, i looked at another part of code (too late and need to rest). I confirm that "yes / no" works fine, but "true/false" doesn't work in a Page Builder, and works in a Theme options

**Comment by danyj** [comment] 2016-04-12 22:26
ok, I had issues with booleans since the begining and best thing I did was stay away from them.

**Comment by WPJobs** [comment] 2016-04-12 22:27
@danyj thak you, i believe i should do the same!

**Comment by moldcraft** [comment] 2016-04-13 08:27
@WPJobs instead of waiting for us to release a new Unyson version with the fix, you can add a fix in your theme. Let's say in your view you use:

```php
$value = fw_get_db_settings_option( 'rss_feed/enabled' ); // or $atts['rss_feed']['enabled'];
if ($value === 'true') {
    // ...
}
```

just change it to:

```php
$value = fw_get_db_settings_option( 'rss_feed/enabled' ); // or $atts['rss_feed']['enabled'];
if (in_array($value, array('true', 'yes'), true)) {
    // ...
}
```

that will work with both old saved values and new values.

We will not change the code in Unyson and you will release a theme update now. Is this solution ok for you?

**Comment by WPJobs** [comment] 2016-04-13 08:40
@moldcraft it will work for theme options, but how about Page Builder? e.g.

```
'autoplay' => array(
	'type' => 'multi-picker',
	'label' => false,
	'desc' => false,
	'picker' => array(
		'enabled' => array(
			'label' => esc_html__( 'Autoplay', 'mytheme' ),
			'type' => 'switch',
			'left-choice' => array(
				'value' => 'false',
				'label' => esc_html__( 'Disabled', 'mytheme' )
			),
			'right-choice' => array(
				'value' => 'true',
				'label' => esc_html__( 'Enabled', 'mytheme' )
			),
			'value' => 'false',
		)
	),
	'choices' => array(
		'true' => array(
			'autoplay_speed' => array(
				'type'  => 'text',
				'label' => esc_html__('Autoplay speed', 'mytheme'),
				'desc'  => esc_html__('in milliseconds, e.g.: 2000 = 2 seconds', 'mytheme'),
			),
		)
	)
),
```

"autoplay" also displays as "disabled" https://yadi.sk/i/KZ9qn9Xeqx5Ng

**Comment by moldcraft** [comment] 2016-04-13 09:00
In page builder it doesn't work. You need to replace `"true"` with `"yes" or "enabled"` and `"false"` with `"no" or "disabled"`, then add in view [this fix](https://github.com/ThemeFuse/Unyson/issues/1449#issuecomment-209301041)

**Comment by WPJobs** [comment] 2016-04-13 09:02
but it worked before, you said that backward compatibility will be added, so you're not going to do that?

**Comment by moldcraft** [comment] 2016-04-13 09:05
I proposed [here](https://github.com/ThemeFuse/Unyson/issues/1449#issuecomment-209301041) to not add backward compatibility but you instead to add a fix in your theme. Do you agree with this proposal?

**Comment by moldcraft** [comment] 2016-04-13 09:06
The problem is because of this change https://github.com/ThemeFuse/Unyson/issues/1394

**Comment by WPJobs** [comment] 2016-04-13 09:10
@moldcraft this solution will not work with Page Builder options, so it makes no sence for me. A lot of users who purchased my themes based on Unyson use Page Builder, and half of options are not working because of this change https://github.com/ThemeFuse/Unyson/issues/1394

Now andreiglingeanu, who asked for this update is happy, but 200+ of my customers are shocked

**Comment by danyj** [comment] 2016-04-13 09:21
@moldcraft @WPJobs  in the light of the issue and his users now being kinda stuck until the fix, we should have something like this https://github.com/ThemeFuse/Unyson/issues/1062  in place for Unyson  in theme/manifest.php

    'max_version' => '2.5.0',

optional of course but if used  dev can test the theme few days after the new release, update the max_version for his customers and than customers can update.

**Comment by WPJobs** [comment] 2016-04-13 09:31
@danyj thank you, but what about users who installed 2.5.1 update and did not make a backups, it is not easy to revert Unyson & Extensions to previous version, that's why this problem is so important and urgent for me & my customers

**Comment by danyj** [comment] 2016-04-13 09:34
@WPJobs  for your users is now to late for this , this is just thinking forward , 
if you had this option and used 2.5.0, you would have had a chance to catch the issue , wait for fix and than have your customers update. right now they update every time they see plugin update released and we ( theme dev's ) need to control when they should update, not Unyson .

**Comment by WPJobs** [comment] 2016-04-13 09:39
@danyj not sure how this can help, sorry: e.g.: user can update Unyson once it will see a notification about new update and the message like "Theme requirements not met: Current Framework version is 2.5.1, maximum required version is 2.5.0" will be shown only after update, not before

**Comment by danyj** [comment] 2016-04-13 09:41
>user can update Unyson once it will see a notification about new update and the message like

that what they should not see until you bump the version 
they should not see update for 2.5.1  if you set max at 2.5.0

same like  #1394  just not only for extensions but for Unyson

hide update notice until you bump the version in theme manifest

**Comment by andreiglingeanu** [comment] 2016-04-13 10:03
@danyj I agree on a `max_version` mechanism. This way several functionality can be safely deprecated and replaced with a better one. Theme maintainers will have two options:

1. Update the theme to conform to new standards
2. Stay away from the new updates

It's all about making tradeoffs and that's why versioning exists, at the end of the day.

@WPJobs This change doesn't make particularly myself happy. I think doing having this behavior in the code is confusing and frustrating for everyone.

```
// resolves to string 'false', not boolean false
$value = fw_get_db_settings_option( 'rss_feed/enabled' ); // or $atts['rss_feed']['enabled'];

if ($value) {
    // This will be executed, string 'false' will be promoted to true boolean.
    // ...
}
```

It's a good thing that unyson takes care of such a small but important details. This way we have simpler and more maintainable code in our themes. That's what profit comes from, after all.

**Comment by WPJobs** [comment] 2016-04-13 10:07
@andreiglingeanu i used following construction to validate booleans from Unyson settings, maybe this will be helpful for you too:

```
if( filter_var( fw_get_db_settings_option( 'myoption' ), FILTER_VALIDATE_BOOLEAN ) ) {
/** so true **/
}
```

**Comment by andreiglingeanu** [comment] 2016-04-13 10:19
@WPJobs The one you suggest happily handles string values as well as boolean ones:

```php
if (filter_var(true, FILTER_VALIDATE_BOOLEAN)) {
  // this one will execute
}

if (filter_var('true', FILTER_VALIDATE_BOOLEAN)) {
  // this one will execute also
}

if (filter_var('false', FILTER_VALIDATE_BOOLEAN)) {
  // this one will not be executed
}

if (filter_var(false, FILTER_VALIDATE_BOOLEAN)) {
  // this one will not be executed also
}
```

If you use this particular construction everywhere you should have no problems.

The check for php 5.4:

![](https://i.imgur.com/OuMEVa7.png)

It also works well for newer versions of php.

**Comment by WPJobs** [comment] 2016-04-13 10:23
@andreiglingeanu p.s. i undersnad that 

```
if ($value) {
    // This will be executed, string 'false' will be promoted to true boolean.
    // ...
}
```

is better than 

```
if( filter_var( fw_get_db_settings_option( 'myoption' ), FILTER_VALIDATE_BOOLEAN ) ) {
/** so true **/
}
```

but, i believe that backward compatibility tweak should be added to Unyson, because:
1) It had no such restrictions before (my code worked fine)
2) these restrictions have not been described in the documentation
3) many users us my themes and they want to have their site worked steadily

thank you all for answers! i hope this problem will be fixed very soon

**Comment by moldcraft** [comment] 2016-04-13 10:27
the problem is not in filter_var, the problem is that on modal save `'true'` is transformed in `true` and switch inside multi-picker [is not recognizing it](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/includes/option-types/switch/class-fw-option-type-switch.php#L122) as known value (right or left choice) and [returns default value](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/includes/option-types/switch/class-fw-option-type-switch.php#L125)

**Comment by moldcraft** [comment] 2016-04-13 11:36
@danyj Do you remember why we added the fix for boolean values for options modal?

When I [comment this line](https://github.com/ThemeFuse/Unyson/blob/v2.5.1/framework/core/components/backend.php#L1137) everything works fine, so I am confused why that fix was added.

**Comment by moldcraft** [comment] 2016-04-13 11:49
I added this in shortcode options.php and everything works fine.

```php
$options = array(
	'rss_feed' => array(
		'type' => 'multi-picker',
		'label' => false,
		'desc' => false,
		'picker' => array(
			'enabled' => array(
				'label' => esc_html__( 'RSS Feed', 'mytheme' ),
				'type' => 'switch',
				'left-choice' => array(
					'value' => 'false',
					'label' => esc_html__( 'Disabled', 'mytheme' )
				),
				'right-choice' => array(
					'value' => 'true',
					'label' => esc_html__( 'Enabled', 'mytheme' )
				),
				'value' => 'true',
			)
		),
		'choices' => array(
			'true' => array(

				'display_thumbnails_in_rss' => array(
					'label' => esc_html__( 'Add post thumbnails to the RSS Feed', 'mytheme' ),
					'type' => 'switch',
					'desc' => esc_html__( 'If enabled, post thumbnail will be added for each post in your RSS feed', 'mytheme' ),
					'right-choice' => array(
						'value' => 'true',
						'label' => esc_html__( 'Yes', 'mytheme' )
					),
					'left-choice' => array(
						'value' => 'false',
						'label' => esc_html__( 'No', 'mytheme' )
					),
					'value' => 'true',
				),

			),
		),
		'show_borders' => false,
	),
	'my_option' => array(
		'label' => __('Some option', 'textdomain'),
		'type' => 'switch',
		'value' => 0,
		'right-choice' => array(
			'value' => 1,
			'label' => __( 'Yes', 'textdomain' )
		),
		'left-choice' => array(
			'value' => 0,
			'label' => __( 'No', 'textdomain' )
		),
	),
	'hello' => array(
		'type' => 'checkboxes',
		'choices' => array(
			true => 'One',
			false => 'Zero',
			'true' => '"True"',
			'false' => '"False"',
		),
	),
	'test-popup' => array(
		'type' => 'popup',
		'popup-options' => array(
			'test-multi' => array(
				'type' => 'multi',
				'label' => false,
				'inner-options' => array(
					'test-switch' => array(
						'type' => 'switch'
					),
					'test-checkboxes' => array(
						'type' => 'checkboxes',
						'choices' => array(
							'text' => 'Text',
							1 => '1',
							0 => '0',
						),
					),
					'test-radio' => array(
						'type' => 'radio',
						'choices' => array(
							'text' => 'Text',
							1 => '1',
							0 => '0',
						),
					),
				),
			),
		),
	),
	'ssadas' => array(
		'type'  => 'switch',
		'label' => __('Activate', 'fw' ),
		'right-choice' => array(
			'value' => true,
			'label' => __( 'Activate', 'fw' )
		),
		'left-choice'  => array(
			'value' => false,
			'label' => __( 'No', 'fw' )
		),
		'value'  => fw_akg('boxshadow/active', $option['value']),
		'attr'   => array(
			'class' => 'boxshadow-active'
		),
	),
	'saddfgdfgdfgd' => array(
		'type'  => 'checkbox',
		'value' => true, // checked/unchecked
		'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
		'label' => __('Label', 'fw'),
		'desc'  => __('Description', 'fw'),
		'help'  => __('Help tip', 'fw'),
		'text'  => __('Yes', 'fw'),
	),
	'test-popup2' => array(
		'type' => 'popup',
		'popup-options' => array(
			'test-multi' => array(
				'type' => 'multi',
				'label' => false,
				'inner-options' => array(
					'test-switch' => array(
						'value'=> true,
						'type'  => 'switch',
						'label' => __('Activate', 'fw' ),
						'right-choice' => array(
							'value' => true,
							'label' => __( 'Activate', 'fw' )
						),
						'left-choice'  => array(
							'value' => false,
							'label' => __( 'No', 'fw' )
						),
						'value'  => true,
					),
					'test-checkboxes' => array(
						'type'  => 'checkbox',
						'value' => true,
						'label' => __('Label', 'fw'),
						'text'  => __('Yes', 'fw'),
					),
					'test-radio' => array(
						'type' => 'radio',
						'value'=> 'active',
						'choices' => array(
							'text' => 'Text',
							'active' => 'Hello',
							'inactive' => 'World',
						),
					),
				),
			),
		),
	),
);
```

**Comment by WPJobs** [comment] 2016-04-13 11:57
@moldcraft sorry, is this message addressed to me or to danyj?

**Comment by moldcraft** [comment] 2016-04-13 12:05
danyj

**Comment by danyj** [comment] 2016-04-13 12:38
@moldcraft  as far as I know for radios we had issues with it 
https://github.com/ThemeFuse/Unyson/issues/670

and there was something about multipicker but I cant remember, still digging

**Comment by danyj** [comment] 2016-04-13 12:48
@moldcraft   I think is because of switch , radio and check inside the modal , #670 and #642 and that is before @andreiglingeanu  suggested his fix, 

il download master now and test those again

**Comment by danyj** [comment] 2016-04-13 12:55
looks ok for me , @WPJobs  you are production ready and need this before we do, so use it if it helps and we will  report an issue if we have one. 

@moldcraft  I strongly suggest the `max_version `so that things like this dont brake production ready sites.

**Comment by WPJobs** [comment] 2016-04-13 13:04
@danyj please, clarify, should i suggest this fix https://github.com/ThemeFuse/Unyson/commit/3d58ca5b5fb88720510cf3bfd46d9e395358d0f8 for my customers before an update will be released?

**Comment by moldcraft** [comment] 2016-04-13 13:04
@WPJobs Yes

**Comment by WPJobs** [comment] 2016-04-13 13:05
@moldcraft @danyj thank you so much!

**Comment by danyj** [comment] 2016-04-13 13:05
yes yes , as @moldcraft  said , I dont know when that was added and why but if it helps your customers , yes tell them to get  that fix. we will fix our things as we go along.

**Comment by moldcraft** [comment] 2016-04-13 13:06
Today we will create an [approval](https://github.com/ThemeFuse/Unyson-Extensions-Approval) and tomorrow the release will be live.

**Comment by WPJobs** [comment] 2016-04-13 13:07
Thank you so much for your time you have spent on this issue! I really appreciate it, and thank you very very much!

**Comment by moldcraft** [comment] 2016-04-13 13:08
Please [follow this](https://github.com/ThemeFuse/Unyson-Extensions-Approval) and test your theme before the new versions will be live.

**Comment by WPJobs** [comment] 2016-04-13 13:09
@moldcraft now i will, necessarily

**Closed** 2016-04-13 14:08 UTC
Labels: in progress

**Comment by danyj** [comment] 2016-04-14 13:23
@moldcraft   
>Please follow this and test your theme before the new versions will be live.

there are hand full of us who are doing this and test daily, but think of this , I  go on a vacation or I am sick or anything that is  stopping me from checking the updates and you release an update that can potentially brake some option in my fresh cool  theme. I am doomed and my customers as well. So please think again about `max_version`  which can help us to stay away from these mistakes. 

with max_version , I am free to think or not think about next Unyson update. Again it should be optional and it would benefit everyone.
