### ISSUE TITLE
Maintenance Mode re-writing permalinks 

### ISSUE THREAD

**Issue by studio500** [ThemeFuse/Unyson#2705] opened 2017-07-16 09:44 UTC
My site was in maintenance mode whilst I updated some areas but a problem arose whereby the content of my Pages would always return a 404 error.
If permalinks were updated, the Pages would be visible for a few seconds before disappearing again  with 404 error.
After weeks of investigation and even moving to a different hosting company, I found out that Unyson Maintenance mode was the issue when it was activated along with Buddypress.

This has caused me a huge headache including loss of data and two months downtime.

I just hope that this can be looked at to prevent it from happening to others.

Apart from that, keep up the good work.

**Comment by danyj** [comment] 2017-07-19 15:54
Unyson maintenance mode? 
looks like that is your theme provider extension not default framework.

**Comment by ViorelEremia** [comment] 2017-08-18 12:57
We tested compatibility with Buddypress and everything was fine.
It would be great if you could to inspect it more strongly or to help us to reproduce this issue in our end.

**Comment by danyj** [comment] 2017-08-18 12:58
@ViorelEremia  dont close this 

it is related to 

https://github.com/ThemeFuse/Unyson/issues/2703  and it has not been looked at

**Comment by ViorelEremia** [comment] 2017-08-30 09:46
https://github.com/ThemeFuse/Unyson/issues/2703

**Closed by ViorelEremia** 2017-08-30 09:46 UTC
