### ISSUE TITLE
Polylang and builder issues

### ISSUE THREAD

**Issue by vm-apreau** [ThemeFuse/Unyson#1059] opened 2015-11-30 17:02 UTC
Hi, 

I have a problem with the Visual page builder. 

I explain, I build my content with block and layout. I saved and my content was correctly display. 

After maybe 2 days, I wanted to modify my content and now the content is empty... and this on many page on the admin wordpress. 

On the frontend, the content is still there only if I don't push the button "modify" in admin wordpress.

![2015-11-30_11h52_21](https://cloud.githubusercontent.com/assets/7883376/11478156/6229124e-9759-11e5-93e7-952a425e159a.png)

When I look on developer Tools, I see an error js (see screenshot).

![2015-11-30_11h52_43](https://cloud.githubusercontent.com/assets/7883376/11478199/9863c1e2-9759-11e5-87e0-f0d92edf2a54.png)

Could you please help me ?

**Comment by moldcraft** [comment] 2015-11-30 17:16
Please do

* Right click (on page) -> View page source
* Ctrl+F: `fw_options[page-builder]`
* Select and copy the value from `value="..."` ([screenshot](http://static.md/733dfe322fdf113e597cdbe8c9da3c01.png))
* Paste it here so we can see where it is broken. Or if you don't want to share the value publicly, send it to `moldcraft[at]email.com`

Then also try to restore the page from [revisions](https://static.md/b52fe7b80a4a5f3ce5d821c36e35ee6b.png)

**Comment by vm-apreau** [comment] 2015-11-30 18:03
I sent you an email ! :) 

Thank you for quick answers !

**Comment by moldcraft** [comment] 2015-12-01 10:09
In your JSON, in text, `"` [are not escaped](https://static.md/16c2c73d9ae3cfe30829bbbf03c9a4c4.png), must be `\"`

I tried to reproduce this in my side, I copy/pasted the same text in a text block shortcode, but everything [works fine](https://static.md/05b9ae1bc4c744450a20b175b41e2a19.png)

Maybe you did something on your site that removed those slashes?

**Comment by vm-apreau** [comment] 2015-12-01 14:36
I have noticed a other bug maybe it's link I don't know. 

But I use Polylang for translate my content. 

When I use Visual page Builder and I add a new page in english (the block are already create with the french content and it's not normal because it's a new page so the content will be empty) and I translate my content. 

After to click on Publish. The content are both updated in wordpress admin. But not in Frontend. 

I explain when I open my french page in wordpress admin, I see the content in english. But the frontend is fine, but if I click on publish in my french page the frontend will be updated with the english content. This is very weird !! 

I hope you understand my problem... it's not easy to explain. 

Thanks in advance !

**Comment by vm-apreau** [comment] 2015-12-02 16:24
Could you please help me ?

Thank you ! :)

**Comment by moldcraft** [comment] 2015-12-03 11:15
Please address this question on [Polylang support page](https://wordpress.org/support/plugin/polylang).

When we will have time to investigate this, we will let you know our results *(this seems to be 80% an issue on Polylang side)*

**Comment by llemurya** [comment] 2015-12-03 13:09
@vm-apreau please see this [video](https://youtu.be/3C-U2xB-wx0) as a proof that our `Page-Builder` works with `Polylang`.The content is copied from the default language and it is the normal behavior if you checked in the 'Polylang' settings page to do this sync . If you just installed `Polylang` go to the settings tab ![alt text](https://static.md/39c0f44cef244c7f281b003f12344e61.png) and click on `Save Changes` button to reset the defaults of the `Polylang` because the default value of synchronization is set to `true` . Hope these helps, please give us some feedback. I am waiting for your response.

**Comment by llemurya** [comment] 2015-12-04 20:50
@vm-apreau please give me an answer.

**Comment by vm-apreau** [comment] 2015-12-04 20:55
Hi ! 

I'm sorry, yes this is exactly this ! I check custom fields..

I open a new issue (I don't find it...) but I discover myself the mistake... ;)

Thank you so much for your help !! :)

**Comment by llemurya** [comment] 2015-12-04 21:01
@vm-apreau If the problem was solved you can close this issue.

**Closed** 2015-12-04 21:03 UTC
