### ISSUE TITLE
Sidebar list on pages and posts

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#213] opened 2015-02-02 17:42 UTC
Is there any way possible to have unyson sidebars list on pages and post edit view 
something like this http://screencast.com/t/oJD1EsTsuB
I know that we can extend pages and posts and add custom options that are displayed under the editor 
but I am talking about that side option and list of sidebar + dynamicaly created ones via unyson sidebar extension.

**Comment by moldcraft** [comment] 2015-02-02 18:46
> I know that we can extend pages and posts and add custom options that are displayed under the editor 
> but I am talking about that side option

You can add boxes on the side using [`context` parameter](http://manual.unyson.io/en/latest/options/containers.html#box-parameters-in-post-options).

```php
array(
    'type' => 'box',
    'title' => 'Hello',
    'context' => 'side',
    'options' => array(...),
)
```

> list of sidebar + dynamicaly created ones via unyson sidebar extension.

I will come back later with a reply for this.

**Comment by moldcraft** [comment] 2015-02-02 18:49
> list of sidebar + dynamicaly created ones via unyson sidebar extension.

You want a select with all sidebars to choose a sidebar for post, and also to be able to create/manage sidebars right there, without going to `/wp-admin/widgets.php` ?

**Comment by MoBadawy** [comment] 2015-02-02 18:52
https://github.com/ThemeFuse/Unyson-Sidebars-Extension/issues/1

**Comment by danyj** [comment] 2015-02-02 20:26
@moldcraft  yes, that is what I mean. If we already copy the best with builder and options than let us add that in also. Pick 5 top wp themes on TF, they all have that option in.

**Comment by llemurya** [comment] 2015-03-06 14:25
@danyj We know about this feature, it will be done in next release of the sidebars. This issue is a duplicate of [this](https://github.com/ThemeFuse/Unyson-Sidebars-Extension/issues/1).

**Closed by llemurya** 2015-03-06 14:25 UTC
Labels: question
