### ISSUE TITLE
[bug] fw_current_url()  adding double domain to url

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Unyson#2703] opened 2017-07-14 20:49 UTC
Go in Unyson any extension that has settings, like breadcrumbs, builder seo etc, click on save button , 

seems like there is extra trailing slash in form or something 

breadcrumbs link 

`http://192.168.0.21/Development/WordPress/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=breadcrumbs`

when saved goes to 

`http://192.168.0.21/Development/WordPress/Development/WordPress/wp-admin/admin.php?page=fw-extensions&sub-page=extension&extension=breadcrumbs`

**Comment by danyj** [comment] 2017-07-14 21:02
checked stable version and it is ok , the bug is in current master

**Comment by danyj** [comment] 2017-07-14 21:21
@GheorgheP   

https://github.com/ThemeFuse/Unyson/commit/daf4ef9bf337b8295bafbdb06c753fd57aa8f6db#diff-1a10d08376d32331dbdc651256766d37

**Comment by antoniomangiacapra** [comment] 2017-08-25 09:51
Is it assumed that this has been fixed in the version 2.6.16? Because I can reproduce it right now with Unyson 2.7.6 and WP 4.8.1.

Also some users of our theme have suddenly faced the issue.

**Comment by danyj** [comment] 2017-08-25 12:02
it has been broken since the last change https://github.com/ThemeFuse/Unyson/commit/daf4ef9bf337b8295bafbdb06c753fd57aa8f6db

**Comment by GheorgheP** [comment] 2017-08-28 08:28
@andreiglingeanu @danyj @ViorelEremia
Please test out it too:
- Simple install: `http://mysite.com`
- SSL: `https://mysite.com`
- Subdomain: `http://my.site.com`
- Subdirectory: `http://site.com/my`
- Subdomain subdirectory: `http://my.site.com/wp`
- Local installation: `http://localhost/mysite` || `http://127.0.0.1/mysite`

**Closed** 2017-08-29 08:13 UTC

**Comment by danyj** [comment] 2017-08-29 14:03
tested works

**Comment by 2Fwebd** [comment] 2017-09-10 15:06
@GheorgheP any plan to release that? Not sure why it's only happening since a few weeks but we're getting a lot of tickets about that.
