### ISSUE TITLE
error of get_multimedia_types() in Slider extension

### ISSUE THREAD

**Issue by duongancol** [ThemeFuse/Unyson#650] opened 2015-06-08 13:32 UTC
Hi, my client get this error when create a new slider. Please check it. 
<pre>
Fatal error: Call to a member function get_multimedia_types() on a non-object in /home/mbsays/public_html/kitchen/wp-content/plugins/unyson/framework/extensions/media/extensions/slider/class-fw-extension-slider.php on line 294
</pre>

**Comment by moldcraft** [comment] 2015-06-08 13:48
@llemurya This error happened already 5 times: [1](https://github.com/ThemeFuse/Unyson-PopulationMethods-Extension/issues/1), [2](https://github.com/ThemeFuse/Unyson/issues/449), [3](https://github.com/ThemeFuse/Unyson/issues/287), [4](https://github.com/ThemeFuse/Unyson/issues/59), [5](https://github.com/ThemeFuse/Unyson/issues/17).

Please, before calling a method, check if [that child extension](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/a9ce6928476af23bcf956a417749f8a036f15f28/class-fw-extension-slider.php#L293) exists.
Because can be cases, when [db value](https://github.com/ThemeFuse/Unyson-Sliders-Extension/blob/a9ce6928476af23bcf956a417749f8a036f15f28/class-fw-extension-slider.php#L290) contains a child extension name that no longer exists.

In the past [I made](https://github.com/ThemeFuse/Unyson-PopulationMethods-Extension/commit/ddab6c50daade069c704acc8b4274500c30c20c5?diff=split) this kind of fixes in the PopulationMethods extension.

**Comment by moldcraft** [comment] 2015-06-09 10:09
https://www.youtube.com/watch?v=wgp91_oJKqY

**Comment by moldcraft** [comment] 2015-06-09 12:32
> @duongancol Hi, my client get this error when create a new slider

How the client went to that error? The same steps as in the video above or something different?

**Comment by duongancol** [comment] 2015-06-09 13:52
it's the same because he's my client.

**Comment by duongancol** [comment] 2015-06-09 15:06
@llemurya after updating slider extension, it showed another error when creating a new slider:
<pre>
This slider was created correctly, but the code implementation was delete from source code or blocked from filter.Delete this post or recovery slider implementation
</pre>

**Comment by llemurya** [comment] 2015-06-10 05:29
@duongancol you can reproduce this bug, because normally this must appear only on the source code of the slider is deleted, but not when you create a new slider. I want to know how to reproduce it to understand what happens and to fix it. Thanks a lot.

**Comment by llemurya** [comment] 2015-06-10 07:17
@duongancol please give us a response, because I can't reproduce this bug.

**Comment by duongancol** [comment] 2015-06-10 07:19
please wait, my client is recording a video. I'll send you soon

**Comment by duongancol** [comment] 2015-06-10 07:29
@llemurya  you can check this video: https://www.youtube.com/watch?v=4lHJrWvK9vk. It's the same process, only different with error message

**Comment by llemurya** [comment] 2015-06-10 07:36
I checked the video .but for me it works.What is why I want to know more details.

**Comment by duongancol** [comment] 2015-06-10 07:38
you can give me an email, I'll send wp-admin account for you.

**Comment by llemurya** [comment] 2015-06-10 07:38
lllemurya@gmail.com

**Comment by duongancol** [comment] 2015-06-10 08:00
Is your email correct one?

**Comment by llemurya** [comment] 2015-06-10 08:03
sorry I make an mistake , please copy and resend the mail , I edited the last comment.

**Comment by duongancol** [comment] 2015-06-11 17:29
Hi @llemurya : is there any news?

**Comment by koetsuji** [comment] 2015-06-18 14:55
Hi. Are there any updates about this? This is really urgent, my boss is making a lot of pressure on me.

**Comment by duongancol** [comment] 2015-06-19 02:52
@koetsuji : did you try deactivate HT-Styling plugin?

**Comment by llemurya** [comment] 2015-06-19 05:10
@duongancol and @koetsuji In the next version of the Unyson it will be fixed.Now I fixed it temporary on the client server side,sorry for the late reply guys.

**Comment by duongancol** [comment] 2015-06-19 05:49
@llemurya Thank you so much for your helps

**Closed** 2015-06-19 12:01 UTC
Labels: bug
