### ISSUE TITLE
color and fond picker

### ISSUE THREAD

**Issue by tkocalka** [ThemeFuse/Unyson#2863] opened 2017-09-07 07:39 UTC
Hi i have big problem. When i give text block I can not change the color and fonts because  it will not show me drop down menu. please help me. please answer me on email

**Comment by ivandotv** [comment] 2017-09-07 13:00
I think this is a duplicate of #2732

**Comment by ViorelEremia** [comment] 2017-09-07 13:15
Try to install latest changes from GitHub master and check if the issue still exists.

**Closed by ViorelEremia** 2017-09-07 13:15 UTC
